import type { Product, Brand, Category, HeroSlide } from "@/types";

// ── Brands ────────────────────────────────────────────────
export const brands: Brand[] = [
  { id: "b1", name: "Milwaukee", slug: "milwaukee", logo: null, featured: true },
  { id: "b2", name: "DeWalt", slug: "dewalt", logo: null, featured: true },
  { id: "b3", name: "Bosch", slug: "bosch", logo: null, featured: true },
  { id: "b4", name: "Makita", slug: "makita", logo: null, featured: true },
  { id: "b5", name: "Stanley", slug: "stanley", logo: null, featured: true },
  { id: "b6", name: "3M", slug: "3m", logo: null, featured: true },
  { id: "b7", name: "Honda", slug: "honda", logo: null, featured: false },
  { id: "b8", name: "Klein Tools", slug: "klein-tools", logo: null, featured: false },
  { id: "b9", name: "Toro", slug: "toro", logo: null, featured: false },
  { id: "b10", name: "EGO", slug: "ego", logo: null, featured: false },
  { id: "b11", name: "Metabo HPT", slug: "metabo-hpt", logo: null, featured: false },
  { id: "b12", name: "FLEX", slug: "flex", logo: null, featured: false },
  { id: "b13", name: "STIHL", slug: "stihl", logo: null, featured: false },
  { id: "b14", name: "FEIN", slug: "fein", logo: null, featured: false },
  { id: "b15", name: "SKIL", slug: "skil", logo: null, featured: false },
  { id: "b16", name: "Festool", slug: "festool", logo: null, featured: false },
  { id: "b17", name: "JET", slug: "jet", logo: null, featured: false },
  { id: "b18", name: "Knaack", slug: "knaack", logo: null, featured: false },
];

// ── Categories ────────────────────────────────────────────
export const categories: Category[] = [
  {
    id: "c1", name: "Herramientas Eléctricas", slug: "herramientas-electricas",
    parentId: null, image: null, icon: "Zap", order: 1,
    children: [
      { id: "c1-1", name: "Taladros", slug: "taladros", parentId: "c1", image: null, icon: "CircleDot", order: 1 },
      { id: "c1-2", name: "Atornilladores", slug: "atornilladores", parentId: "c1", image: null, icon: "Settings", order: 2 },
      { id: "c1-3", name: "Sierras", slug: "sierras", parentId: "c1", image: null, icon: "Scissors", order: 3 },
      { id: "c1-4", name: "Esmeriladoras", slug: "esmeriladoras", parentId: "c1", image: null, icon: "Disc", order: 4 },
      { id: "c1-5", name: "Rotomartillos", slug: "rotomartillos", parentId: "c1", image: null, icon: "Hammer", order: 5 },
    ],
  },
  {
    id: "c2", name: "Herramientas Manuales", slug: "herramientas-manuales",
    parentId: null, image: null, icon: "Wrench", order: 2,
    children: [
      { id: "c2-1", name: "Llaves", slug: "llaves", parentId: "c2", image: null, icon: "Wrench", order: 1 },
      { id: "c2-2", name: "Pinzas", slug: "pinzas", parentId: "c2", image: null, icon: "Grip", order: 2 },
      { id: "c2-3", name: "Destornilladores", slug: "destornilladores", parentId: "c2", image: null, icon: "Screwdriver", order: 3 },
      { id: "c2-4", name: "Martillos", slug: "martillos", parentId: "c2", image: null, icon: "Hammer", order: 4 },
    ],
  },
  {
    id: "c3", name: "Jardín y Exterior", slug: "jardin-exterior",
    parentId: null, image: null, icon: "Trees", order: 3,
  },
  {
    id: "c4", name: "Seguridad Industrial", slug: "seguridad-industrial",
    parentId: null, image: null, icon: "Shield", order: 4,
  },
  {
    id: "c5", name: "Servicio Técnico Milwaukee", slug: "servicio-tecnico-milwaukee",
    parentId: null, image: null, icon: "Settings", order: 5,
  },
  {
    id: "c6", name: "Accesorios", slug: "accesorios",
    parentId: null, image: null, icon: "Package", order: 6,
  },
  {
    id: "c7", name: "Almacenamiento", slug: "almacenamiento",
    parentId: null, image: null, icon: "HardHat", order: 7,
  },
  {
    id: "c8", name: "Medición", slug: "medicion",
    parentId: null, image: null, icon: "Ruler", order: 8,
  },
];

// ── Products ──────────────────────────────────────────────
export const products: Product[] = [
  // ── Taladros Milwaukee ──
  {
    id: "p1", sku: "MIL-2801-20", name: "Taladro Percutor M18 FUEL 1/2\" Milwaukee",
    slug: "taladro-percutor-m18-fuel-12-milwaukee",
    description: "El Taladro Percutor M18 FUEL de 1/2\" cuenta con el motor POWERSTATE Brushless de Milwaukee, que ofrece hasta 60% más potencia que los taladros con cable. Con el sistema REDLINK PLUS Intelligence, el taladro proporciona un rendimiento óptimo al protegerse contra sobrecargas, sobrecalentamientos y descargas excesivas. Incluye 2 baterías M18 XC5.0 de alta capacidad, cargador M18 y maletín.",
    shortDescription: "Motor brushless POWERSTATE. Hasta 1,200 RPM y 18,000 BPM. Kit con 2 baterías XC5.0.",
    price: 2899.00, comparePrice: 3499.00,
    categoryId: "c1-1", brandId: "b1", brand: brands[0], category: categories[0]?.children?.[0],
    stock: 15, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Tipo de Motor": "Brushless POWERSTATE",
      "Velocidad (RPM)": "0-550 / 0-1,800", "Golpes por Minuto (BPM)": "0-18,500 / 0-31,500",
      "Mandril": "1/2\" metálico de 3 quijadas", "Capacidad Máx. Concreto": "1-1/4\"",
      "Peso": "5.3 lb (2.4 kg)", "Garantía": "5 años herramienta / 2 años batería",
    },
    rating: 4.8, reviewCount: 124, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p2", sku: "MIL-2802-20", name: "Taladro Percutor Compacto M18 1/2\" Milwaukee",
    slug: "taladro-percutor-compacto-m18-12-milwaukee",
    description: "Taladro percutor compacto de la serie M18 diseñado para espacios reducidos sin sacrificar potencia. Cuenta con motor brushless, mandril de 1/2\" y solo 3.4 lb de peso, ideal para trabajos prolongados. Kit incluye 2 baterías M18 CP2.0, cargador y maletín.",
    shortDescription: "Ultra compacto. Solo 3.4 lb. Mandril 1/2\". Kit con 2 baterías CP2.0.",
    price: 1799.00, comparePrice: 2199.00,
    categoryId: "c1-1", brandId: "b1", brand: brands[0], category: categories[0]?.children?.[0],
    stock: 22, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Tipo de Motor": "Brushless",
      "Velocidad (RPM)": "0-450 / 0-1,700", "Peso": "3.4 lb (1.5 kg)",
      "Mandril": "1/2\"", "Longitud": "7.0\"",
    },
    rating: 4.6, reviewCount: 87, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── Atornilladores Milwaukee ──
  {
    id: "p3", sku: "MIL-2953-20", name: "Impacto Inalámbrico M18 FUEL 1/4\" Hex Milwaukee",
    slug: "impacto-inalambrico-m18-fuel-14-hex-milwaukee",
    description: "El Impacto Inalámbrico M18 FUEL 1/4\" Hex de Milwaukee ofrece hasta 2,000 in-lbs de par de apriete, el más potente de su clase. Cuenta con el motor POWERSTATE Brushless de 4 polos y tecnología REDLINK PLUS. Kit completo con 2 baterías M18 XC5.0.",
    shortDescription: "2,000 in-lbs de par. El más potente de su clase. Kit con 2 baterías XC5.0.",
    price: 2599.00, comparePrice: 3099.00,
    categoryId: "c1-2", brandId: "b1", brand: brands[0], category: categories[0]?.children?.[1],
    stock: 18, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Par Máximo": "2,000 in-lbs",
      "Velocidad (RPM)": "0-3,500", "Golpes por Minuto": "0-4,300",
      "Peso": "3.1 lb (1.4 kg)", "Garantía": "5 años",
    },
    rating: 4.9, reviewCount: 203, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── Sierras Milwaukee ──
  {
    id: "p4", sku: "MIL-2730-20", name: "Sierra Circular M18 FUEL 7-1/4\" Milwaukee",
    slug: "sierra-circular-m18-fuel-714-milwaukee",
    description: "Sierra circular con el motor POWERSTATE Brushless de Milwaukee que corta hasta 600 pies de tablero OSB por carga. El sistema REDLITHIUM XC5.0 proporciona hasta 370 cortes por carga. Incluye disco de 7-1/4\" y maletín.",
    shortDescription: "Motor brushless POWERSTATE. Hasta 600 pies de corte por carga. Disco 7-1/4\" incluido.",
    price: 2199.00, comparePrice: 2699.00,
    categoryId: "c1-3", brandId: "b1", brand: brands[0], category: categories[0]?.children?.[2],
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Diámetro de Disco": "7-1/4\"",
      "Profundidad de Corte (90°)": "2-7/16\"", "Profundidad de Corte (45°)": "1-15/16\"",
      "Velocidad sin Carga": "5,800 RPM", "Peso": "5.5 lb (2.5 kg)",
    },
    rating: 4.7, reviewCount: 76, isFeatured: true, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p5", sku: "MIL-2520-20", name: "Sierra Caladora M18 FUEL Milwaukee",
    slug: "sierra-caladora-m18-fuel-milwaukee",
    description: "La Sierra Caladora M18 FUEL de Milwaukee es la primera sierra caladora que elimina los desafíos que los usuarios han enfrentado con las sierras caladoras inalámbricas. Hasta 30% más potencia y el sistema ONE-KEY para personalización.",
    shortDescription: "30% más potencia que la generación anterior. Systema ONE-KEY. Cortes limpios en madera y metal.",
    price: 1599.00, comparePrice: null,
    categoryId: "c1-3", brandId: "b1", brand: brands[0], category: categories[0]?.children?.[2],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Velocidad Variable": "0-3,000 SPM",
      "Capacidad de Corte Madera": "2-3/4\"", "Capacidad de Corte Metal": "3/8\"",
      "Peso": "5.1 lb (2.3 kg)", "Longitud de Golpe": "1\"",
    },
    rating: 4.5, reviewCount: 54, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  // ── Rotomartillos ──
  {
    id: "p6", sku: "MIL-2715-20", name: "Rotomartillo SDS-Plus M18 FUEL 1-1/8\" Milwaukee",
    slug: "rotomartillo-sds-plus-m18-fuel-118-milwaukee",
    description: "El Rotomartillo SDS-Plus M18 FUEL de Milwaukee ofrece la potencia de un taladro con cable en formato inalámbrico. Con el motor POWERSTATE Brushless, proporciona 1.7 ft-lbs de energía de impacto. Ideal para perforación pesada en concreto.",
    shortDescription: "1.7 ft-lbs de energía de impacto. SDS-Plus. Kit con 2 baterías XC5.0.",
    price: 3299.00, comparePrice: 3899.00,
    categoryId: "c1-5", brandId: "b1", brand: brands[0], category: categories[0]?.children?.[4],
    stock: 6, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Energía de Impacto": "1.7 ft-lbs (EPTA)",
      "Velocidad (RPM)": "0-1,250 / 0-2,100", "Golpes por Minuto": "0-4,600 / 0-7,800",
      "Tipo de Encastre": "SDS-Plus", "Diámetro Máx. Concreto": "1-1/8\"",
      "Peso": "6.2 lb (2.8 kg)",
    },
    rating: 4.9, reviewCount: 92, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── Esmeriladoras ──
  {
    id: "p7", sku: "MIL-2864-20", name: "Esmeriladora Angular M18 FUEL 4-1/2\" - 5\" Milwaukee",
    slug: "esmeriladora-angular-m18-fuel-45-5-milwaukee",
    description: "La Esmeriladora Angular M18 FUEL de 4-1/2\" / 5\" es la primera esmeriladora inalámbrica que supera el rendimiento de las herramientas con cable. Sistema de frenado REDLITHIUM que detiene el disco en menos de 2 segundos.",
    shortDescription: "Supera el rendimiento de herramientas con cable. Frenado en <2 seg. Kit completo.",
    price: 1899.00, comparePrice: 2299.00,
    categoryId: "c1-4", brandId: "b1", brand: brands[0], category: categories[0]?.children?.[3],
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Diámetro de Disco": "4-1/2\" - 5\"",
      "Velocidad sin Carga": "8,500 RPM", "Interruptor": "Sin retención / con retención (ambos incluidos)",
      "Peso": "4.8 lb (2.2 kg)", "Longitud": "12.3\"",
    },
    rating: 4.7, reviewCount: 68, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── DeWalt Products ──
  {
    id: "p8", sku: "DW-DCD791D2", name: "Taladro Inalámbrico DeWalt 20V MAX XR 1/2\"",
    slug: "taladro-inalambrico-dewalt-20v-max-xr-12",
    description: "Taladro DeWalt 20V MAX XR con motor brushless de alta eficiencia. Cuenta con 2 velocidades, mandril de 1/2\" metal rígido y LED integrado con modo de 20 segundos de retardo. Kit incluye 2 baterías 2.0Ah.",
    shortDescription: "Motor brushless XR. 2 velocidades. LED de 20 seg. Kit con 2 baterías 2.0Ah.",
    price: 1699.00, comparePrice: 1999.00,
    categoryId: "c1-1", brandId: "b2", brand: brands[1], category: categories[0]?.children?.[0],
    stock: 20, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "20V MAX", "Motor": "Brushless",
      "Velocidad": "0-650 / 0-2,000 RPM", "Mandril": "1/2\" metal rígido",
      "Peso": "3.4 lb", "Batería Incluida": "2x 2.0Ah",
    },
    rating: 4.5, reviewCount: 145, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p9", sku: "DW-DCF887D2", name: "Impacto DeWalt 20V MAX XR 1/4\" Hex",
    slug: "impacto-dewalt-20v-max-xr-14-hex",
    description: "Impacto inalámbrico DeWalt con motor brushless XR de 3 velocidades. Ofrece hasta 1,825 in-lbs de par de apriete con modo de precisión a 3 velocidades. Compacto y liviano para máxima maniobrabilidad.",
    shortDescription: "3 velocidades. 1,825 in-lbs de par. Modo de precisión. Kit con 2 baterías.",
    price: 1499.00, comparePrice: 1799.00,
    categoryId: "c1-2", brandId: "b2", brand: brands[1], category: categories[0]?.children?.[1],
    stock: 25, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "20V MAX", "Par Máximo": "1,825 in-lbs",
      "Velocidad": "0-400 / 0-1,200 / 0-1,750 / 0-2,250 RPM",
      "Peso": "3.4 lb", "Garantía": "3 años limitada",
    },
    rating: 4.6, reviewCount: 178, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── Bosch Products ──
  {
    id: "p10", sku: "BOS-GBH18V-28DK", name: "Taladro Percutor Bosch 18V 1/2\" con Kit",
    slug: "taladro-percutor-bosch-18v-12-con-kit",
    description: "Taladro percutor Bosch 18V con tecnología brushless de alto rendimiento. Máxima potencia en perforación de madera, metal y concreto. Diseño ergonómico con empuñadura suave. Kit con 2 baterías ProCore18V 4.0Ah.",
    shortDescription: "Brushless ECC. Ergonómico. Kit con 2 baterías ProCore 4.0Ah.",
    price: 2199.00, comparePrice: null,
    categoryId: "c1-1", brandId: "b3", brand: brands[2], category: categories[0]?.children?.[0],
    stock: 14, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Par Máximo (duro)": "57 Nm",
      "Velocidad": "0-500 / 0-1,900 RPM", "Peso": "1.7 kg",
      "Batería": "2x ProCore18V 4.0Ah", "Garantía": "3 años",
    },
    rating: 4.4, reviewCount: 63, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p11", sku: "BOS-GSR18V-190", name: "Taladro Destornillador Bosch 18V EC Brushless",
    slug: "taladro-destornillador-bosch-18v-ec-brushless",
    description: "Taladro destornillador Bosch 18V con motor EC Brushless para mayor durabilidad y tiempos de ejecución. 20 posiciones de torque para una gran variedad de aplicaciones. Incluye 2 baterías 2.0Ah.",
    shortDescription: "Motor EC Brushless. 20 posiciones de torque. Compacto y ligero.",
    price: 1199.00, comparePrice: 1499.00,
    categoryId: "c1-2", brandId: "b3", brand: brands[2], category: categories[0]?.children?.[1],
    stock: 30, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Par Máximo": "54 Nm (duro)",
      "Velocidad": "0-500 / 0-1,900 RPM", "Torque": "20+1 posiciones",
      "Peso": "1.5 kg",
    },
    rating: 4.3, reviewCount: 91, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── Herramientas Manuales ──
  {
    id: "p12", sku: "STN-90-947", name: "Juego de Llaves Combinadas Stanley 14 Piezas 1/4\" - 3/4\"",
    slug: "juego-llaves-combinadas-stanley-14-piezas",
    description: "Juego de 14 llaves combinadas Stanley con acabado cromado brillante. Fabricadas en acero al carbono de alta calidad con restricción de torque. Incluye maletín de plástico para almacenamiento organizado.",
    shortDescription: "14 llaces combinadas. Acero cromado. Maletín incluido.",
    price: 189.00, comparePrice: 249.00,
    categoryId: "c2-1", brandId: "b5", brand: brands[4], category: categories[1]?.children?.[0],
    stock: 50, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Cantidad de Piezas": "14", "Tamaño": "1/4\" a 3/4\"",
      "Material": "Acero al carbono cromado", "Acabado": "Cromado brillante",
      "Tipo": "Combinadas (boca + estrella)",
    },
    rating: 4.5, reviewCount: 234, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p13", sku: "STN-20-045", name: "Juego de Destornilladores Stanley 10 Piezas",
    slug: "juego-destornilladores-stanley-10-piezas",
    description: "Juego de 10 destornilladores Stanley con puntas magnéticas. Mango bi-material ergonómico para mayor comodidad. Incluye destornilladores de punta plana y Phillips en diferentes tamaños.",
    shortDescription: "10 piezas. Puntas magnéticas. Mango ergonómico bi-material.",
    price: 79.90, comparePrice: 99.90,
    categoryId: "c2-3", brandId: "b5", brand: brands[4], category: categories[1]?.children?.[2],
    stock: 75, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Cantidad": "10 piezas", "Tipo de Puntas": "Plana y Phillips",
      "Mango": "Bi-material", "Magnetizado": "Sí",
    },
    rating: 4.2, reviewCount: 156, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p14", sku: "STN-84-098", name: "Cinta Métrica Stanley 25ft x 1\" POWERLOCK",
    slug: "cinta-metrica-stanley-25ft-powerlock",
    description: "Cinta métrica Stanley POWERLOCK de 25 pies con diseño duradero y resistente. Caja de plástico resistente a impactos, gancho de cinta de 3 remaches y marcaciones fáciles de leer.",
    shortDescription: "25 pies. POWERLOCK. Resistente a impactos. 3 remaches en gancho.",
    price: 49.90, comparePrice: null,
    categoryId: "c8", brandId: "b5", brand: brands[4], category: categories[7],
    stock: 100, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Longitud": "25 ft (7.5m)", "Ancho de Cinta": "1\" (25mm)",
      "Material Cinta": "Acero", "Tipo": "POWERLOCK",
    },
    rating: 4.6, reviewCount: 312, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  // ── Seguridad Industrial ──
  {
    id: "p15", sku: "3M-1100-132501", name: "Protectores Auditivos 3M Peltor Optime",
    slug: "protectores-auditivos-3m-peltor-optime",
    description: "Protectores auditivos 3M Peltor Optime diseñados para entornos de alto ruido industrial. Reducción de ruido de 30 dB. Diadema ajustable y almohadillas reemplazables para máxima comodidad durante todo el día.",
    shortDescription: "NRR 30 dB. Diadema ajustable. Almohadillas reemplazables. Uso industrial.",
    price: 159.00, comparePrice: null,
    categoryId: "c4", brandId: "b6", brand: brands[5], category: categories[3],
    stock: 40, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Reducción de Ruido (NRR)": "30 dB", "Tipo": "Diadema (over-ear)",
      "Material": "ABS / espuma", "Uso": "Industrial",
      "Certificación": "ANSI S3.19",
    },
    rating: 4.4, reviewCount: 87, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p16", sku: "3M-11650", name: "Gafas de Seguridad 3M Virtua con Lente Clara",
    slug: "gafas-seguridad-3m-virtua-lente-clara",
    description: "Gafas de seguridad 3M Virtua con lente clara anti-rayas. Montura ligera en policarbonato, protector de nariz integrado y protección UV400. Ideales para entornos de trabajo donde se requiere protección ocular básica.",
    shortDescription: "Lente anti-rayas. UV400. Montura ligera. Paquete de 12 unidades.",
    price: 189.00, comparePrice: 228.00,
    categoryId: "c4", brandId: "b6", brand: brands[5], category: categories[3],
    stock: 60, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Cantidad": "12 unidades", "Lente": "Clara anti-rayas",
      "Material Montura": "Policarbonato", "Protección UV": "UV400",
      "Certificación": "ANSI Z87.1",
    },
    rating: 4.3, reviewCount: 145, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── More Milwaukee ──
  {
    id: "p17", sku: "MIL-49-24-0216", name: "Kit de Baterías M18 REDLITHIUM XC5.0 (2 unidades)",
    slug: "kit-baterias-m18-redlithium-xc5-2-unidades",
    description: "Kit de 2 baterías Milwaukee M18 REDLITHIUM XC5.0 de 5.0Ah. Proporcionan hasta 2.5x más tiempo de ejecución, 20% más potencia y 2x más recargas que las baterías estándar. Compatible con toda la línea M18.",
    shortDescription: "2x 5.0Ah. 2.5x más duración. Compatible con toda la línea M18.",
    price: 1199.00, comparePrice: 1499.00,
    categoryId: "c6", brandId: "b1", brand: brands[0], category: categories[5],
    stock: 35, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Capacidad": "5.0 Ah", "Voltaje": "18V",
      "Tecnología": "REDLITHIUM XC", "Células": "18650 premium",
      "Temperatura Operación": "-20°C a 60°C",
    },
    rating: 4.8, reviewCount: 267, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p18", sku: "MIL-48-59-1812", name: "Cargador Rápido M18/M12 Milwaukee",
    slug: "cargador-rapido-m18-m12-milwaukee",
    description: "Cargador de baterías rápido Milwaukee compatible con los sistemas M18 y M12. Carga una batería M18 XC5.0 en solo 60 minutos. Diseño compacto con indicadores LED de estado de carga y protección contra sobrecarga.",
    shortDescription: "Compatible M18/M12. Carga en 60 min. Indicadores LED.",
    price: 399.00, comparePrice: null,
    categoryId: "c6", brandId: "b1", brand: brands[0], category: categories[5],
    stock: 45, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Compatible con": "M18 y M12", "Tiempo de Carga XC5.0": "~60 min",
      "Voltaje Entrada": "120V", "Peso": "1.1 lb",
    },
    rating: 4.7, reviewCount: 189, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  // ── Almacenamiento ──
  {
    id: "p19", sku: "MIL-48-22-8425", name: "Organizador Modular Milwaukee PACKOUT 2 Piezas",
    slug: "organizador-modular-milwaukee-packout-2-piezas",
    description: "Sistema de almacenamiento modular Milwaukee PACKOUT con 2 organizadores. Cuentas con 11 compartimientos removibles en el organizador superior y protección IP65 contra polvo y agua. Se conectan entre sí y con otros componentes PACKOUT.",
    shortDescription: "2 organizadores. 11 compartimientos. IP65. Sistema modular PACKOUT.",
    price: 449.00, comparePrice: 549.00,
    categoryId: "c7", brandId: "b1", brand: brands[0], category: categories[6],
    stock: 20, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Compartimientos": "11 removibles", "Protección": "IP65 (polvo y agua)",
      "Material": "Polipropileno de impacto", "Sistema": "PACKOUT modular",
      "Peso": "3.5 lb",
    },
    rating: 4.6, reviewCount: 98, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p20", sku: "MIL-48-22-8430", name: "Caja de Herramientas PACKOUT Rolling Milwaukee",
    slug: "caja-herramientas-packout-rolling-milwaukee",
    description: "Caja de herramientas rodante Milwaukee PACKOUT de 22 pulgadas. Ruedas de 9\" todo terreno, asa retráctil y capacidad de carga de 100 lb. Interior amplio con organizador removible. Compatible con todo el ecosistema PACKOUT.",
    shortDescription: "22\" rodante. Ruedas 9\" todo terreno. 100 lb capacidad. PACKOUT.",
    price: 799.00, comparePrice: 999.00,
    categoryId: "c7", brandId: "b1", brand: brands[0], category: categories[6],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Capacidad": "100 lb", "Ruedas": "9\" todo terreno",
      "Interior": "30.5\" x 16.5\" x 14\"", "Material": "Polipropileno de impacto",
      "Protección": "IP65",
    },
    rating: 4.9, reviewCount: 56, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── Makita ──
  {
    id: "p21", sku: "MKT-XRFO1Z", name: "Rotomartillo SDS-Plus Makita 18V LXT Brushless",
    slug: "rotomartillo-sds-plus-makita-18v-lxt-brushless",
    description: "Rotomartillo Makita 18V LXT con motor brushless de alta eficiencia. Ofrece 3 modos de operación: solo rotación, rotación con percusión y solo percusión. Con sistema XPT (Extreme Protection Technology) contra polvo y agua.",
    shortDescription: "3 modos de operación. Brushless. XPT (resistente al polvo/agua).",
    price: 2499.00, comparePrice: 2899.00,
    categoryId: "c1-5", brandId: "b4", brand: brands[3], category: categories[0]?.children?.[4],
    stock: 11, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Voltaje": "18V", "Energía de Impacto": "1.7 Joules",
      "Velocidad (RPM)": "0-680 / 0-1,200 / 0-2,350",
      "Golpes por Minuto": "0-4,600 / 0-8,200 / 0-17,500",
      "Encastre": "SDS-Plus", "Protección": "XPT",
    },
    rating: 4.5, reviewCount: 72, isFeatured: false, isOnSale: true, isNewArrival: true,
  },
  // ── More manual tools ──
  {
    id: "p22", sku: "STN-84-106", name: "Nivel de Burbuja Stanley 24\" Torpedo",
    slug: "nivel-burbuja-stanley-24-torpedo",
    description: "Nivel de burbuja Stanley de 24 pulgadas con 3 viales de precisión (horizontal, vertical y 45°). Cuerpo de aluminio extruido con bordes reforzados. Precisión de 0.0005\" por pulgada.",
    shortDescription: "24\" aluminio. 3 viales de precisión. Precisión 0.0005\"/pulgada.",
    price: 69.90, comparePrice: 89.90,
    categoryId: "c8", brandId: "b5", brand: brands[4], category: categories[7],
    stock: 35, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Longitud": "24\"", "Material": "Aluminio extruido",
      "Viales": "3 (horizontal, vertical, 45°)", "Precisión": "0.0005\"/pulgada",
    },
    rating: 4.4, reviewCount: 167, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p23", sku: "MIL-48-22-2401", name: "Navaja Retráctil Milwaukee FASTBACK 10-1/4\"",
    slug: "navaja-retractil-milwaukee-fastback-10-14",
    description: "Navaja retráctil Milwaukee FASTBACK con apertura de una sola mano y cambio de hoja rápido sin herramientas. Mango ergonómico con inserto de goma para agarre firme. Incluye 5 hojas extra.",
    shortDescription: "Apertura 1 mano. Cambio rápido de hoja. Incluye 5 hojas extra.",
    price: 89.90, comparePrice: null,
    categoryId: "c2", brandId: "b1", brand: brands[0], category: categories[1],
    stock: 55, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Longitud Abierto": "10-1/4\"", "Cambio de Hoja": "Sin herramientas",
      "Hojas Incluidas": "5 extra", "Material Mango": "Aluminio + goma",
    },
    rating: 4.7, reviewCount: 289, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p24", sku: "MIL-48-59-1202", name: "Set de Puntas y Bitas Milwaukee SHOCKWAVE 60 Piezas",
    slug: "set-puntas-bitas-milwaukee-shockwave-60-piezas",
    description: "Set completo de 60 piezas Milwaukee SHOCKWAVE con punta de impacto, bitas Phillips, Torx, Hex y Square. Geometría SHOCKWAVE para mayor durabilidad. Compatible con todos los impactos de 1/4\".",
    shortDescription: "60 piezas. Geometría SHOCKWAVE. Para impacto. Maletín incluido.",
    price: 349.00, comparePrice: 429.00,
    categoryId: "c6", brandId: "b1", brand: brands[0], category: categories[5],
    stock: 28, images: ["/images/products/placeholder-tool.jpg"],
    specs: {
      "Total de Piezas": "60", "Tipos": "Phillips, Torx, Hex, Square",
      "Compatible con": "Impacto 1/4\" hex", "Maletín": "Incluido",
    },
    rating: 4.8, reviewCount: 198, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── Honda Products ──
  {
    id: "p25", sku: "HON-EU2200I", name: "Generador Inalámbrico Honda EU2200i",
    slug: "generador-inalambrico-honda-eu2200i",
    description: "Generador inalámbrico Honda EU2200i con motor GX100 de 121cc. Ultra silencioso (49-57 dB), ideal para camping, obras y emergencias. Inverter technology para energía limpia y estable. Funciona hasta 8.1 horas con tanque lleno.",
    shortDescription: "2200W. Inverter. Ultra silencioso 49dB. 8.1h autonomía.",
    price: 4599.00, comparePrice: 5299.00,
    categoryId: "c6", brandId: "b7", brand: brands[6], category: categories[5],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "2200W / 1800W rated", "Motor": "GX100 121cc", "Nivel de Ruido": "49-57 dB", "Autonomía": "8.1 horas", "Peso": "46.3 lb" },
    rating: 4.9, reviewCount: 312, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p26", sku: "HON-WB20XT", name: "Motobomba Honda WB20XT 2\"",
    slug: "motobomba-honda-wb20xt",
    description: "Motobomba centrifuga Honda WB20XT de 2 pulgadas con motor GX120 de 118cc. Caudal máximo de 440 GPM. Carcasa de aluminio fundido y impulsor de hierro. Ideal para drenaje, irrigación y construcción.",
    shortDescription: "2 pulgadas. 440 GPM. Motor GX120. Carcasa aluminio.",
    price: 2899.00, comparePrice: null,
    categoryId: "c3", brandId: "b7", brand: brands[6], category: categories[2],
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Caudal Máximo": "440 GPM", "Motor": "GX120 118cc", "Descarga": "2 pulgadas", "Material Carcasa": "Aluminio fundido" },
    rating: 4.7, reviewCount: 89, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p27", sku: "HON-GX160", name: "Motor Honda GX160 5.5HP",
    slug: "motor-honda-gx160-55hp",
    description: "Motor horizontal Honda GX160 de 5.5HP con eje de 3/4 pulgadas. Tecnología OHV para mayor eficiencia de combustible. Arranque fácil y confiable. Ideal para equipos industriales, generadores y bombas.",
    shortDescription: "5.5HP. OHV. Eje 3/4\". Bajo consumo de combustible.",
    price: 1599.00, comparePrice: 1899.00,
    categoryId: "c6", brandId: "b7", brand: brands[6], category: categories[5],
    stock: 15, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "5.5 HP", "Desplazamiento": "163cc", "Eje": "3/4\" x 2-7/16\"", "Combustible": "Gasolina" },
    rating: 4.8, reviewCount: 203, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p28", sku: "HON-EM5000S", name: "Generador Honda EM5000S 5000W",
    slug: "generador-honda-em5000s",
    description: "Generador industrial Honda EM5000S de 5000W con motor GX390. Voltaje dual 120/240V con panel de control completo. Tanque de 6.2 galones para 11.2 horas de operación continua. Protección contra sobrecarga y bajo aceite.",
    shortDescription: "5000W. 120/240V. 11.2h autonomía. Motor GX390.",
    price: 7999.00, comparePrice: 8999.00,
    categoryId: "c6", brandId: "b7", brand: brands[6], category: categories[5],
    stock: 5, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "5000W / 4500W rated", "Motor": "GX390 389cc", "Voltaje": "120/240V", "Tanque": "6.2 gal", "Autonomía": "11.2 horas" },
    rating: 4.6, reviewCount: 67, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p29", sku: "HON-HRX217", name: "Cortacésped Honda HRX217VKA 21\"",
    slug: "cortacesped-honda-hrx217",
    description: "Cortacésped autopropulsado Honda HRX217VKA de 21 pulgadas con motor GCV200. Sistema NeXite resistente a óxido y corrosión. Selective Mulch o Bag con un solo toque. MicroCut twin blades para corte superior.",
    shortDescription: "21\". Autopropulsado. NeXite. MicroCut twin blades.",
    price: 5499.00, comparePrice: null,
    categoryId: "c3", brandId: "b7", brand: brands[6], category: categories[2],
    stock: 7, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Ancho de Corte": "21\"", "Motor": "GCV200 170cc", "Propulsión": "Autopropulsado Select Drive", "Cuchillas": "MicroCut twin" },
    rating: 4.8, reviewCount: 145, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p30", sku: "HON-GASCOMP", name: "Motocompresor Honda GAS 8 Galón",
    slug: "motocompresor-honda-gas",
    description: "Motocompresor de pistón Honda con motor GX160 y tanque de 8 galones. Presión máxima de 135 PSI. Flujo de 5.3 CFM a 90 PSI. Ideal para obras de construcción, pintura y herramientas neumáticas.",
    shortDescription: "8 gal. 135 PSI. 5.3 CFM. Motor GX160.",
    price: 3299.00, comparePrice: 3799.00,
    categoryId: "c6", brandId: "b7", brand: brands[6], category: categories[5],
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Presión Máxima": "135 PSI", "Tanque": "8 galones", "CFM @90PSI": "5.3", "Motor": "GX160 5.5HP" },
    rating: 4.5, reviewCount: 54, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── Klein Tools Products ──
  {
    id: "p31", sku: "KLN-NCVT2", name: "Detector de Voltaje Klein Tools NCVT-2",
    slug: "detector-voltaje-klein-tools-ncvt2",
    description: "Detector de voltaje sin contacto Klein Tools NCVT-2 con sensibilidad dual (12-1000V AC y 48-1000V AC). Indicador LED y alarma sonora. Punta retráctil y clip de bolsillo. Certificado CAT IV 1000V.",
    shortDescription: "Dual rango 12-1000V AC. LED + alarma. CAT IV.",
    price: 189.00, comparePrice: 229.00,
    categoryId: "c8", brandId: "b8", brand: brands[7], category: categories[7],
    stock: 45, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Rango": "12-1000V AC / 48-1000V AC", "Certificación": "CAT IV 1000V", "Alimentación": "2x AAA incluidas" },
    rating: 4.6, reviewCount: 278, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p32", sku: "KLN-CL390", name: "Pinza Amperimétrica Klein Tools CL390",
    slug: "pinza-amperimetrica-klein-cl390",
    description: "Pinza amperimétrica verdadera RMS Klein Tools CL390 con medición AC/DC hasta 400A. Multímetro integrado con funciones de voltaje, resistencia, continuidad y capacitancia. Pantalla LCD retroiluminada con retención de datos.",
    shortDescription: "AC/DC 400A. True RMS. Multímetro integrado. LCD.",
    price: 549.00, comparePrice: null,
    categoryId: "c8", brandId: "b8", brand: brands[7], category: categories[7],
    stock: 30, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Rango AC/DC": "400A", "Funciones": "V, A, Ω, Continuidad, Capacitancia", "Pantalla": "LCD retroiluminada" },
    rating: 4.7, reviewCount: 156, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p33", sku: "KLN-11IN1", name: "Juego de Destornilladores Klein Tools 11 en 1",
    slug: "juego-destornilladores-klein-tools-11-en-1",
    description: "Juego de 11 en 1 Klein Tools con punta de impacto resistente. Incluye bitas Phillips, slotted, square y Torx. Mango ergonómico con giro de 180°. Acero S2 de alta calidad para máxima durabilidad.",
    shortDescription: "11 piezas. Puntas S2. Giro 180°. Mango ergonómico.",
    price: 129.00, comparePrice: 159.00,
    categoryId: "c2-3", brandId: "b8", brand: brands[7], category: categories[1]?.children?.[2] as Category,
    stock: 60, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Piezas": "11", "Material Puntas": "Acero S2", "Tipo": "Phillips, Slotted, Square, Torx" },
    rating: 4.5, reviewCount: 198, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p34", sku: "KLN-25FT", name: "Cinta Métrica Klein Tools 25ft MAGNE-TAPE",
    slug: "cinta-metrica-klein-tools-25ft",
    description: "Cinta métrica Klein Tools de 25 pies con punta magnética para trabajo con una sola mano. Carcasa resistente a impactos con recubrimiento de goma. Marcaciones grandes fáciles de leer. Blindaje de nylon de doble capa.",
    shortDescription: "25 pies. Punta magnética. Impacto resistente. Nylon 2 capas.",
    price: 69.90, comparePrice: null,
    categoryId: "c8", brandId: "b8", brand: brands[7], category: categories[7],
    stock: 80, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Longitud": "25 pies (7.6m)", "Punta": "Magnética", "Blindaje": "Nylon doble capa" },
    rating: 4.4, reviewCount: 234, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p35", sku: "KLN-935RBTS", name: "Nivel de Mango Klein Tools 24\" RAPIDBIND",
    slug: "nivel-mango-klein-tools-24",
    description: "Nivel de mango Klein Tools de 24 pulgadas con cuerpo de aluminio extruido. Bloque de lectura RAPIDBIND de alta visibilidad. 3 viales de precisión (horizontal, vertical y 45°). Topes de goma antisocavación.",
    shortDescription: "24\" aluminio. RAPIDBIND. 3 viales. Topes antisocavación.",
    price: 399.00, comparePrice: 479.00,
    categoryId: "c8", brandId: "b8", brand: brands[7], category: categories[7],
    stock: 20, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Longitud": "24\"", "Material": "Aluminio extruido", "Viales": "3 (H, V, 45°)", "Precisión": "0.0005\"/pulgada" },
    rating: 4.8, reviewCount: 87, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p36", sku: "KLN-1105", name: "Pelacables Klein Tools 1105",
    slug: "pelacables-klein-tools-1105",
    description: "Pelacables Klein Tools 1105 para cables AWG 10-22. Mandíbulas de acero forjado con tratamiento térmico. Mango de dos colores con resorte integrado. Corta y pela en un solo paso con ajuste de longitud.",
    shortDescription: "AWG 10-22. Acero forjado. Mango bicol. Corta y pela.",
    price: 149.00, comparePrice: null,
    categoryId: "c2-2", brandId: "b8", brand: brands[7], category: categories[1]?.children?.[1] as Category,
    stock: 55, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Rango AWG": "10-22", "Material": "Acero forjado", "Función": "Corta y pela" },
    rating: 4.6, reviewCount: 167, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  // ── Toro Products ──
  {
    id: "p37", sku: "TOR-51621", name: "Soplador de Hojas Toro 51621 Ultra",
    slug: "soplador-hojas-toro-51621",
    description: "Soplador de hojas Toro 51621 con motor eléctrico de alto rendimiento. Velocidad variable con turbo boost hasta 250 MPH. Peso ligero de solo 7.5 lb para uso prolongado sin fatiga. Ideal para jardines medianos y grandes.",
    shortDescription: "250 MPH turbo. Velocidad variable. 7.5 lb. Eléctrico.",
    price: 699.00, comparePrice: 849.00,
    categoryId: "c3", brandId: "b9", brand: brands[8], category: categories[2],
    stock: 18, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Velocidad Máxima": "250 MPH", "Motor": "Eléctrico", "Peso": "7.5 lb" },
    rating: 4.3, reviewCount: 189, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p38", sku: "TOR-20339", name: "Cortacésped Toro Recycler 22\" AutoMower",
    slug: "cortacesped-toro-recycler-22",
    description: "Cortacésped Toro Recycler de 22 pulgadas con sistema de corte Recycler que devuelve nutrientes al césped. Motor Briggs & Stratton de 163cc. Autopropulsado con Personal Pace. Sistema de lavado integrado.",
    shortDescription: "22\" Recycler. Briggs & Stratton 163cc. Autopropulsado.",
    price: 2499.00, comparePrice: 2899.00,
    categoryId: "c3", brandId: "b9", brand: brands[8], category: categories[2],
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Ancho de Corte": "22\"", "Motor": "Briggs & Stratton 163cc", "Sistema": "Recycler", "Propulsión": "Personal Pace" },
    rating: 4.5, reviewCount: 112, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p39", sku: "TOR-51480", name: "Podadora de Setos Toro 51480 20\"",
    slug: "podadora-toro-51480",
    description: "Podadora de setos Toro de 20 pulgadas con cuchillas de doble filo de alto carbono. Motor de 4.4 amp para cortes limpios. Mango ergonómico con empuñadura auxiliar. Ligera y equilibrada para reducir la fatiga.",
    shortDescription: "20\" doble filo. 4.4 amp. Mango ergonómico. Ligera.",
    price: 399.00, comparePrice: null,
    categoryId: "c3", brandId: "b9", brand: brands[8], category: categories[2],
    stock: 25, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Longitud de Cuchilla": "20\"", "Motor": "4.4 amp", "Cuchillas": "Doble filo alto carbono" },
    rating: 4.2, reviewCount: 76, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p40", sku: "TOR-60VBLOW", name: "Soplador Inalámbrico Toro 60V MAX",
    slug: "soplador-inalambrico-toro-60v",
    description: "Soplador inalámbrico Toro 60V MAX con tecnología de motor brushless. Hasta 630 CFM de flujo de aire con velocidad variable. Batería de 60V para máxima potencia. Ideal para limpieza pesada de hojas y escombros.",
    shortDescription: "60V MAX. 630 CFM. Brushless. Velocidad variable.",
    price: 1599.00, comparePrice: 1899.00,
    categoryId: "c3", brandId: "b9", brand: brands[8], category: categories[2],
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "60V MAX", "Flujo de Aire": "630 CFM", "Motor": "Brushless" },
    rating: 4.6, reviewCount: 93, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p41", sku: "TOR-20368", name: "Limpiadora a Presión Toro 20368 2030 PSI",
    slug: "limpiadora-presion-toro-20368",
    description: "Limpiadora a presión Toro 20368 de 2030 PSI con motor OHV de 163cc. Flujo de 1.76 GPM para limpieza eficiente. 3 boquillas de rociado y tanque de detergente integrado. Ideal para terrazas, vehículos y fachadas.",
    shortDescription: "2030 PSI. 1.76 GPM. 3 boquillas. Motor OHV 163cc.",
    price: 1299.00, comparePrice: null,
    categoryId: "c3", brandId: "b9", brand: brands[8], category: categories[2],
    stock: 15, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Presión": "2030 PSI", "Flujo": "1.76 GPM", "Motor": "OHV 163cc", "Boquillas": "3 incluidas" },
    rating: 4.4, reviewCount: 67, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p42", sku: "TOR-20333", name: "Cortadora de Césped Toro 20333 22\" SmartStow",
    slug: "cortadora-cesped-toro-20333",
    description: "Cortadora de césped Toro 22\" con sistema SmartStow para almacenamiento vertical que ahorra hasta 70% de espacio. Motor Briggs & Stratton 163cc con sistemas Recycler y Bag. 3 opciones de descarga en una sola herramienta.",
    shortDescription: "22\" SmartStow. 163cc. 3 modos descarga. Ahorra 70% espacio.",
    price: 899.00, comparePrice: 1099.00,
    categoryId: "c3", brandId: "b9", brand: brands[8], category: categories[2],
    stock: 20, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Ancho de Corte": "22\"", "Motor": "Briggs & Stratton 163cc", "Sistema": "SmartStow vertical" },
    rating: 4.3, reviewCount: 54, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── EGO Products ──
  {
    id: "p43", sku: "EGO-580CFM", name: "Soplador de Mochila EGO POWER+ 580 CFM",
    slug: "mochila-soplador-ego-power-580cfm",
    description: "Soplador de mochila EGO POWER+ con motor brushless de alta eficiencia. 580 CFM de flujo de aire con turbo boost hasta 145 MPH. Batería 56V ARC Lithium para hasta 90 minutos de autonomía. Arnés ergonómico acolchado.",
    shortDescription: "580 CFM. 56V ARC Lithium. 90 min autonomía. Arnés ergonómico.",
    price: 2199.00, comparePrice: 2599.00,
    categoryId: "c3", brandId: "b10", brand: brands[9], category: categories[2],
    stock: 14, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Flujo de Aire": "580 CFM", "Velocidad": "Hasta 145 MPH", "Voltaje": "56V", "Autonomía": "Hasta 90 min" },
    rating: 4.8, reviewCount: 203, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p44", sku: "EGO-LM2102SP", name: "Cortacésped EGO LM2102SP 56V 21\"",
    slug: "cortacesped-ego-lm2102sp-56v",
    description: "Cortacésped autopropulsado EGO POWER+ de 21 pulgadas con motor brushless de 56V. Sistema KICK BACK BAR para arranque instantáneo. 6 posiciones de corte de 1.25\" a 4\". Batería incluida para hasta 60 minutos.",
    shortDescription: "21\". 56V brushless. Autopropulsado. 6 posiciones de corte.",
    price: 3299.00, comparePrice: 3799.00,
    categoryId: "c3", brandId: "b10", brand: brands[9], category: categories[2],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Ancho de Corte": "21\"", "Motor": "56V Brushless", "Altura de Corte": "1.25\"-4\" (6 pos.)", "Autonomía": "Hasta 60 min" },
    rating: 4.7, reviewCount: 156, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p45", sku: "EGO-CS1604", name: "Sierra de Cadena EGO POWER+ 56V 16\"",
    slug: "sierra-cadena-ego-56v-16",
    description: "Sierra de cadena inalámbrica EGO POWER+ de 16 pulgadas con motor brushless de 56V. Sistema de tensión sin herramientas. Freno de cadena automático y protector de mano. Lubricación automática con tanque de 6.8 oz.",
    shortDescription: "16\". 56V brushless. Tensión sin herramientas. Freno automático.",
    price: 1899.00, comparePrice: 2199.00,
    categoryId: "c1-3", brandId: "b10", brand: brands[9], category: categories[0]?.children?.[2] as Category,
    stock: 11, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Longitud de Guía": "16\"", "Voltaje": "56V", "Velocidad de Cadena": "5800 FPM", "Lubricación": "Automática" },
    rating: 4.6, reviewCount: 89, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p46", sku: "EGO-DRILL56V", name: "Taladro Percutor EGO POWER+ 56V 1/2\"",
    slug: "taladro-percutor-ego-56v",
    description: "Taladro percutor EGO POWER+ de 56V con motor brushless y mandril de 1/2\" sin llave. 2 velocidades con modo percusión para concreto. LED de trabajo integrado. Compatible con todas las baterías EGO 56V ARC Lithium.",
    shortDescription: "56V brushless. 1/2\" mandril. 2 velocidades + percusión. LED.",
    price: 1299.00, comparePrice: null,
    categoryId: "c1-1", brandId: "b10", brand: brands[9], category: categories[0]?.children?.[0] as Category,
    stock: 18, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "56V", "Mandril": "1/2\" sin llave", "Velocidades": "0-550 / 0-2,000 RPM", "Peso": "4.4 lb" },
    rating: 4.4, reviewCount: 67, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p47", sku: "EGO-TRIM56V", name: "Recortabordes EGO POWER+ 56V",
    slug: "recortabordes-ego-56v",
    description: "Recortabordes inalámbrico EGO POWER+ de 56V con motor brushless. Ancho de corte de 15 pulgadas con cabezal de carga rápida. Mango telescópico ajustable y empuñadura auxiliar. Hasta 45 minutos de autonomía por carga.",
    shortDescription: "56V. 15\" corte. Cabezal rápido. Mango telescópico. 45 min.",
    price: 799.00, comparePrice: 949.00,
    categoryId: "c3", brandId: "b10", brand: brands[9], category: categories[2],
    stock: 22, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "56V", "Ancho de Corte": "15\"", "Autonomía": "Hasta 45 min", "Tipo de Línea": "0.080\" enrollable" },
    rating: 4.5, reviewCount: 112, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p48", sku: "EGO-BA750", name: "Batería EGO 56V ARC Lithium 7.5Ah",
    slug: "bateria-ego-56v-arc-lithium-75ah",
    description: "Batería EGO 56V ARC Lithium de 7.5Ah con tecnología de celdas avanzadas. Indicador LED de carga integrado. Compatible con toda la línea EGO POWER+. Protección contra sobrecarga, sobredescarga y sobrecalentamiento.",
    shortDescription: "56V 7.5Ah. ARC Lithium. LED indicador. Compatible toda la línea.",
    price: 999.00, comparePrice: 1199.00,
    categoryId: "c6", brandId: "b10", brand: brands[9], category: categories[5],
    stock: 30, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "56V", "Capacidad": "7.5 Ah", "Tecnología": "ARC Lithium", "Peso": "2.43 lb" },
    rating: 4.9, reviewCount: 234, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── Metabo HPT Products ──
  {
    id: "p49", sku: "MHB-NR83A5", name: "Clavadora Neumática Metabo HPT NR83A5",
    slug: "clavadora-neumatica-metabo-hpt-nr83a5",
    description: "Clavadora neumática de marco Metabo HPT NR83A5 para clavos de 2\" a 3-1/4\". Mecanismo de accionamiento selectivo (secuencial o contacto). Capacidad de cargador de 64 clavos. Ligera de solo 7.5 lb.",
    shortDescription: "2\"-3-1/4\". 64 clavos cargador. 7.5 lb. Selective actuation.",
    price: 1899.00, comparePrice: 2199.00,
    categoryId: "c1", brandId: "b11", brand: brands[10], category: categories[0],
    stock: 16, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Clavos": "2\" a 3-1/4\"", "Cargador": "64 clavos", "Peso": "7.5 lb", "Presión": "70-120 PSI" },
    rating: 4.6, reviewCount: 134, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p50", sku: "MHB-DH36VPA", name: "Rotomartillo SDS-Plus Metabo HPT DH36VPA 36V",
    slug: "rotomartillo-metabo-hpt-dh36vpa",
    description: "Rotomartillo SDS-Plus Metabo HPT DH36VPA de 36V con motor brushless. 3 modos: taladro, taladro percutor y solo cincel. Energía de impacto de 1.7 ft-lbs. Sistema de vibración reducida para mayor comodidad.",
    shortDescription: "36V brushless. 3 modos. 1.7 ft-lbs. Vibración reducida.",
    price: 2499.00, comparePrice: null,
    categoryId: "c1-5", brandId: "b11", brand: brands[10], category: categories[0]?.children?.[4] as Category,
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "36V Multivolt", "Impacto": "1.7 ft-lbs", "Modos": "3 (taladro, percutor, cincel)", "Encastre": "SDS-Plus" },
    rating: 4.5, reviewCount: 87, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p51", sku: "MHB-CIRC18V", name: "Sierra Circular Metabo HPT 18V 6-1/2\"",
    slug: "sierra-circular-metabo-hpt-18v",
    description: "Sierra circular inalámbrica Metabo HPT de 6-1/2\" con motor brushless de 18V. Profundidad de corte de 2-1/16\" a 90°. Base de aluminio fundido para precisión. Luz LED de trabajo y freno eléctrico.",
    shortDescription: "18V brushless. 6-1/2\". Base aluminio. LED + freno eléctrico.",
    price: 1399.00, comparePrice: 1699.00,
    categoryId: "c1-3", brandId: "b11", brand: brands[10], category: categories[0]?.children?.[2] as Category,
    stock: 20, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Disco": "6-1/2\"", "Profundidad 90°": "2-1/16\"", "Peso": "5.7 lb" },
    rating: 4.4, reviewCount: 76, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p52", sku: "MHB-DRILL18V", name: "Taladro Percutor Metabo HPT 18V Brushless 1/2\"",
    slug: "taladro-percutor-metabo-hpt-18v-brushless",
    description: "Taladro percutor Metabo HPT 18V con motor brushless de alta eficiencia. Mandril de 1/2\" sin llave. 2 velocidades con 22 posiciones de torque. LED de trabajo con modo de 20 segundos. Kit con 2 baterías 2.0Ah.",
    shortDescription: "18V brushless. 1/2\". 2 velocidades. 22 torque. Kit 2 baterías.",
    price: 1599.00, comparePrice: null,
    categoryId: "c1-1", brandId: "b11", brand: brands[10], category: categories[0]?.children?.[0] as Category,
    stock: 14, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Torque": "442 in-lbs", "Velocidades": "0-500 / 0-1,900 RPM", "Mandril": "1/2\" sin llave" },
    rating: 4.3, reviewCount: 98, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p53", sku: "MHB-GRIND18V", name: "Esmeriladora Angular Metabo HPT 18V 4-1/2\"",
    slug: "esmeriladora-angular-metabo-hpt-18v",
    description: "Esmeriladora angular Metabo HPT de 4-1/2\" con motor brushless de 18V. Interruptor de palanca sin retención para seguridad. Freno eléctrico que detiene el disco en segundos. Disco de 4-1/2\" incluido.",
    shortDescription: "18V brushless. 4-1/2\". Freno eléctrico. Disco incluido.",
    price: 1199.00, comparePrice: 1499.00,
    categoryId: "c1-4", brandId: "b11", brand: brands[10], category: categories[0]?.children?.[3] as Category,
    stock: 18, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Disco": "4-1/2\"", "Velocidad": "9,100 RPM", "Peso": "4.2 lb" },
    rating: 4.5, reviewCount: 65, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p54", sku: "MHB-NV65AH2", name: "Clavadora de Techo Metabo HPT NV65AH2",
    slug: "clavadora-techo-metabo-hpt-nv65ah2",
    description: "Clavadora de techo Metabo HPT NV65AH2 para clavos de 1-1/4\" a 2-1/2\". Cargador de 200 clavos para máxima productividad. Mecanismo de disparo secuencial con ajuste de profundidad sin herramientas. Ligera de 7.3 lb.",
    shortDescription: "1-1/4\"-2-1/2\". 200 clavos. Ajuste profundidad sin herramientas.",
    price: 2299.00, comparePrice: 2699.00,
    categoryId: "c1", brandId: "b11", brand: brands[10], category: categories[0],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Clavos": "1-1/4\" a 2-1/2\"", "Cargador": "200 clavos", "Peso": "7.3 lb", "Presión": "70-120 PSI" },
    rating: 4.7, reviewCount: 112, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── FLEX Products ──
  {
    id: "p55", sku: "FLX-24VDRILL", name: "Taladro Percutor FLEX 24V 1/2\" Brushless",
    slug: "taladro-percutor-flex-24v-12",
    description: "Taladro percutor FLEX de 24V con motor brushless de alto torque. Mandril de 1/2\" metal rígido. 2 velocidades con 25 posiciones de torque. LED de trabajo con modo retardo. Kit con 2 baterías 4.0Ah.",
    shortDescription: "24V brushless. 1/2\". 2 velocidades. 25 torque. Kit 2 bat.",
    price: 1799.00, comparePrice: 2099.00,
    categoryId: "c1-1", brandId: "b12", brand: brands[11], category: categories[0]?.children?.[0] as Category,
    stock: 15, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "24V", "Torque": "1,300 in-lbs", "Velocidades": "0-550 / 0-2,100 RPM", "Peso": "3.9 lb" },
    rating: 4.5, reviewCount: 89, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p56", sku: "FLX-24VIMPACT", name: "Impacto FLEX 24V 1/4\" Hex Brushless",
    slug: "impacto-flex-24v-14-hex",
    description: "Impacto inalámbrico FLEX de 24V con motor brushless de 4 polos. Hasta 1,700 in-lbs de par de apriete. 3 velocidades con modo de precisión. LED de trabajo con 3 modos de iluminación. Compacto y potente.",
    shortDescription: "24V. 1,700 in-lbs. 3 velocidades. Modo precisión. LED 3 modos.",
    price: 1499.00, comparePrice: null,
    categoryId: "c1-2", brandId: "b12", brand: brands[11], category: categories[0]?.children?.[1] as Category,
    stock: 20, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "24V", "Par Máximo": "1,700 in-lbs", "Velocidades": "0-900 / 0-2,100 / 0-3,200 RPM", "Peso": "3.0 lb" },
    rating: 4.4, reviewCount: 67, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p57", sku: "FLX-24VCIRC", name: "Sierra Circular FLEX 24V 7-1/4\" Brushless",
    slug: "sierra-circular-flex-24v-714",
    description: "Sierra circular FLEX de 7-1/4\" con motor brushless de 24V. Corte de hasta 2-9/16\" a 90°. Base de magnesio ligera y resistente. Freno eléctrico para seguridad. Luz LED integrada y disco incluido.",
    shortDescription: "24V. 7-1/4\". Base magnesio. Freno eléctrico. LED.",
    price: 1699.00, comparePrice: 1999.00,
    categoryId: "c1-3", brandId: "b12", brand: brands[11], category: categories[0]?.children?.[2] as Category,
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "24V", "Disco": "7-1/4\"", "Profundidad 90°": "2-9/16\"", "Base": "Magnesio" },
    rating: 4.6, reviewCount: 54, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p58", sku: "FLX-24VGRIND", name: "Esmeriladora Angular FLEX 24V 4-1/2\"-5\"",
    slug: "esmeriladora-angular-flex-24v-45",
    description: "Esmeriladora angular FLEX de 4-1/2\" a 5\" con motor brushless de 24V. Interruptor de gatillo con retención de seguridad. Freno eléctrico que detiene el disco en menos de 2 segundos. Empuñadura lateral ajustable.",
    shortDescription: "24V. 4-1/2\"-5\". Freno eléctrico. Empuñadura ajustable.",
    price: 1299.00, comparePrice: null,
    categoryId: "c1-4", brandId: "b12", brand: brands[11], category: categories[0]?.children?.[3] as Category,
    stock: 18, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "24V", "Disco": "4-1/2\" a 5\"", "Velocidad": "8,500 RPM", "Peso": "4.6 lb" },
    rating: 4.3, reviewCount: 45, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p59", sku: "FLX-24VROTO", name: "Rotomartillo SDS-Plus FLEX 24V Brushless",
    slug: "rotomartillo-sds-plus-flex-24v",
    description: "Rotomartillo SDS-Plus FLEX de 24V con motor brushless. 3 modos: taladro, taladro percutor y cincel. Energía de impacto de 2.0 ft-lbs. Sistema anti-vibración para confort en uso prolongado. Kit con 2 baterías.",
    shortDescription: "24V brushless. 3 modos. 2.0 ft-lbs. Anti-vibración. Kit 2 bat.",
    price: 2899.00, comparePrice: 3299.00,
    categoryId: "c1-5", brandId: "b12", brand: brands[11], category: categories[0]?.children?.[4] as Category,
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "24V", "Impacto": "2.0 ft-lbs", "Encastre": "SDS-Plus", "Modos": "3" },
    rating: 4.7, reviewCount: 78, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p60", sku: "FLX-24VBAT2PK", name: "Kit 2 Baterías FLEX 24V 4.0Ah + Cargador",
    slug: "kit-2-baterias-flex-24v-40ah-cargador",
    description: "Kit de 2 baterías FLEX de 24V 4.0Ah con tecnología de celdas avanzadas. Cargador rápido de 30 minutos incluido. Indicador LED de estado de carga. Compatible con toda la línea de herramientas FLEX 24V.",
    shortDescription: "2x 4.0Ah 24V. Cargador 30 min. LED. Compatible línea FLEX.",
    price: 999.00, comparePrice: 1199.00,
    categoryId: "c6", brandId: "b12", brand: brands[11], category: categories[5],
    stock: 25, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "24V", "Capacidad": "4.0 Ah c/u", "Tiempo de Carga": "~30 min", "Células": "Li-ion avanzadas" },
    rating: 4.5, reviewCount: 134, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── STIHL Products ──
  {
    id: "p61", sku: "STI-MS250", name: "Motosierra STIHL MS 250 18\"",
    slug: "motosierra-stihl-ms-250",
    description: "Motosierra STIHL MS 250 de 18 pulgadas con motor 2-MIX de alta eficiencia. Sistema anti-vibración para menor fatiga. Freno de cadena manual e inercial. Arranque fácil con compensador y bomba de cebado.",
    shortDescription: "18\". 2-MIX. Anti-vibración. Freno manual + inercial.",
    price: 2299.00, comparePrice: 2699.00,
    categoryId: "c3", brandId: "b13", brand: brands[12], category: categories[2],
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Guía": "18\"", "Motor": "2-MIX", "Potencia": "3.0 HP", "Peso": "10.1 lb" },
    rating: 4.8, reviewCount: 267, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p62", sku: "STI-BG86", name: "Soplador de Hojas STIHL BG 86 Gasolina",
    slug: "soplador-hojas-stihl-bg-86",
    description: "Soplador de hojas STIHL BG 86 con motor a gasolina de alta potencia. Velocidad de aire de hasta 190 MPH. Tubo redondeado para flujo óptimo. Sistema anti-vibración y empuñadura ergonómica. Arranque fácil ElastoStart.",
    shortDescription: "190 MPH. Gasolina. ElastoStart. Anti-vibración. Tubo redondeado.",
    price: 1299.00, comparePrice: null,
    categoryId: "c3", brandId: "b13", brand: brands[12], category: categories[2],
    stock: 16, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Velocidad de Aire": "190 MPH", "Motor": "Gasolina 2-MIX", "Peso": "9.3 lb", "Arranque": "ElastoStart" },
    rating: 4.6, reviewCount: 189, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p63", sku: "STI-FS120", name: "Desbrozadora STIHL FS 120 Gasolina",
    slug: "desbrozadora-stihl-fs-120",
    description: "Desbrozadora STIHL FS 120 con motor 2-MIX y sistema de arranque Easy2Start. Mango en bicicleta para uso profesional prolongado. Cabezal Tap&Go para avance rápido de hilo. Ideal para limpieza de terrenos y maleza densa.",
    shortDescription: "Easy2Start. Mango bicicleta. Tap&Go. Uso profesional.",
    price: 1899.00, comparePrice: 2199.00,
    categoryId: "c3", brandId: "b13", brand: brands[12], category: categories[2],
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Motor": "2-MIX", "Arranque": "Easy2Start", "Mango": "Bicicleta profesional", "Peso": "12.1 lb" },
    rating: 4.5, reviewCount: 145, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p64", sku: "STI-RE110", name: "Hidrolimpiadora STIHL RE 110 Plus",
    slug: "hidrolimpiadora-stihl-re-110",
    description: "Hidrolimpiadora STIHL RE 110 Plus de 1800 PSI con motor eléctrico. Flujo de 1.8 GPM para limpieza eficiente. 3 boquillas de rociado y pistola de alta presión. Sistema de succión de detergente integrado.",
    shortDescription: "1800 PSI. 1.8 GPM. 3 boquillas. Motor eléctrico.",
    price: 899.00, comparePrice: null,
    categoryId: "c3", brandId: "b13", brand: brands[12], category: categories[2],
    stock: 20, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Presión": "1800 PSI", "Flujo": "1.8 GPM", "Boquillas": "3 incluidas", "Motor": "Eléctrico universal" },
    rating: 4.3, reviewCount: 98, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p65", sku: "STI-BP3", name: "Motobomba de Agua STIHL BP 3",
    slug: "motobomba-agua-stihl-bp-3",
    description: "Motobomba de agua STIHL BP 3 con motor 2-MIX de alta potencia. Caudal de hasta 150 GPM con succión de 8 metros. Carcasa de aluminio fundido resistente a la corrosión. Ideal para drenaje e irrigación en obras y campo.",
    shortDescription: "150 GPM. Succión 8m. Carcasa aluminio. Motor 2-MIX.",
    price: 1699.00, comparePrice: 1999.00,
    categoryId: "c3", brandId: "b13", brand: brands[12], category: categories[2],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Caudal": "150 GPM", "Succión": "8 metros", "Motor": "2-MIX", "Carcasa": "Aluminio fundido" },
    rating: 4.7, reviewCount: 67, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p66", sku: "STI-BGA200", name: "Soplador Inalámbrico STIHL BGA 200 36V",
    slug: "soplador-inalambrico-stihl-bga-200",
    description: "Soplador inalámbrico STIHL BGA 200 de 36V con motor brushless EC. Hasta 756 CFM de flujo de aire con boost. Sistema anti-vibración y empuñadura ergonómica. Batería AP 300 incluida para hasta 25 minutos de trabajo.",
    shortDescription: "36V EC brushless. 756 CFM. Boost. AP 300 incluida. 25 min.",
    price: 2499.00, comparePrice: 2899.00,
    categoryId: "c3", brandId: "b13", brand: brands[12], category: categories[2],
    stock: 6, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "36V", "Flujo de Aire": "756 CFM", "Motor": "EC Brushless", "Batería": "AP 300 incluida" },
    rating: 4.8, reviewCount: 54, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── FEIN Products ──
  {
    id: "p67", sku: "FEIN-MM350Q", name: "Multiherramienta FEIN MultiMaster 350Q Top",
    slug: "multiherramienta-fein-multimaster-350q",
    description: "Multiherramienta oscilante FEIN MultiMaster 350Q Top con motor de 350W. Interface QuickIN para cambio de accesorios sin herramientas. Regulación electrónica de velocidad constante. Kit completo con 27 accesorios y maletín.",
    shortDescription: "350W. QuickIN. Velocidad constante. Kit 27 accesorios.",
    price: 3299.00, comparePrice: 3899.00,
    categoryId: "c1", brandId: "b14", brand: brands[13], category: categories[0],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "350W", "Oscilaciones": "12,000-20,000 OPM", "Interface": "QuickIN", "Accesorios": "27 incluidos" },
    rating: 4.9, reviewCount: 178, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p68", sku: "FEIN-MM250Q", name: "Multiherramienta FEIN MultiMaster 250Q",
    slug: "multiherramienta-fein-multimaster-250q",
    description: "Multiherramienta oscilante FEIN MultiMaster 250Q con motor de 250W. Interface QuickIN para cambio rápido de accesorios. Regulación electrónica de velocidad. Incluye 15 accesorios esenciales y maletín de transporte.",
    shortDescription: "250W. QuickIN. Regulación electrónica. 15 accesorios.",
    price: 2499.00, comparePrice: null,
    categoryId: "c1", brandId: "b14", brand: brands[13], category: categories[0],
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "250W", "Oscilaciones": "11,000-18,500 OPM", "Interface": "QuickIN" },
    rating: 4.7, reviewCount: 134, isFeatured: false, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p69", sku: "FEIN-SCC620", name: "Sierra de Calar FEIN SCC 620 1200W",
    slug: "sierra-calar-fein-scc-620",
    description: "Sierra de calar FEIN SCC 620 con motor de 1200W para cortes potentes y precisos. Sistema de cambio rápido de hoja sin herramientas. Base basculante para cortes en ángulo. Regulación electrónica de velocidad con pendular de 4 posiciones.",
    shortDescription: "1200W. Cambio rápido hoja. Base basculante. 4 modos pendular.",
    price: 4199.00, comparePrice: 4799.00,
    categoryId: "c1-3", brandId: "b14", brand: brands[13], category: categories[0]?.children?.[2] as Category,
    stock: 6, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "1200W", "Corte Madera": "120mm", "Corte Metal": "20mm", "Velocidad": "500-3,000 SPM" },
    rating: 4.6, reviewCount: 89, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p70", sku: "FEIN-WPO1465", name: "Pulidora Excenténtrica FEIN WPO 14-65 E 350W",
    slug: "pulidora-excentrica-fein-wpo-14-65-e",
    description: "Pulidora excenténtrica FEIN WPO 14-65 E con motor de 350W y disco de 150mm. Órbita de 5mm para acabado fino sin marcas. Regulación electrónica de velocidad constante. Sistema de fijación velcro para discos de lija.",
    shortDescription: "350W. 150mm. Órbita 5mm. Velocidad constante. Velcro.",
    price: 2899.00, comparePrice: null,
    categoryId: "c1-4", brandId: "b14", brand: brands[13], category: categories[0]?.children?.[3] as Category,
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "350W", "Disco": "150mm (6\")", "Órbita": "5mm", "Velocidad": "6,000-11,000 RPM" },
    rating: 4.5, reviewCount: 56, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p71", sku: "FEIN-BKM2520", name: "Taladro de Columna FEIN BKM 2520 850W",
    slug: "taladro-columna-fein-bkm-2520",
    description: "Taladro de columna FEIN BKM 2520 con motor de 850W y capacidad de taladro en acero de 25mm. Mesa giratoria 360°. Mandril de alta precisión con rango de 2-25mm. Estructura robusta de fundición para máxima estabilidad.",
    shortDescription: "850W. 25mm acero. Mesa 360°. Mandril 2-25mm. Fundición.",
    price: 5499.00, comparePrice: 6299.00,
    categoryId: "c1-1", brandId: "b14", brand: brands[13], category: categories[0]?.children?.[0] as Category,
    stock: 4, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "850W", "Capacidad Acero": "25mm", "Mandril": "2-25mm", "Velocidades": "12" },
    rating: 4.8, reviewCount: 45, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p72", sku: "FEIN-WSE25", name: "Aspiradora Industrial FEIN WSE 25 1400W",
    slug: "aspiradora-industrial-fein-wse-25",
    description: "Aspiradora industrial FEIN WSE 25 con motor de 1400W y capacidad de 25 litros. Sistema de filtro automático para trabajo continuo sin interrupciones. Ideal para polvo fino, virutas y líquidos. Filtro HEPA opcional.",
    shortDescription: "1400W. 25L. Filtro automático. Polvo + líquidos. HEPA opcional.",
    price: 1999.00, comparePrice: 2399.00,
    categoryId: "c6", brandId: "b14", brand: brands[13], category: categories[5],
    stock: 14, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "1400W", "Capacidad": "25 litros", "Filtro": "Automático", "Depresión": "254 mbar" },
    rating: 4.7, reviewCount: 98, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── SKIL Products ──
  {
    id: "p73", sku: "SKL-12VDRILL", name: "Taladro Percutor SKIL 12V 3/8\" CC6811",
    slug: "taladro-percutor-skil-12v",
    description: "Taladro percutor compacto SKIL de 12V con mandril de 3/8\". 2 velocidades con 18 posiciones de torque. LED de trabajo integrado. Ligero de solo 2.5 lb para trabajo prolongado sin fatiga. Incluye 2 baterías 1.5Ah.",
    shortDescription: "12V. 3/8\". 2 velocidades. 2.5 lb. Kit 2 baterías.",
    price: 599.00, comparePrice: 749.00,
    categoryId: "c1-1", brandId: "b15", brand: brands[14], category: categories[0]?.children?.[0] as Category,
    stock: 35, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "12V", "Mandril": "3/8\"", "Torque": "265 in-lbs", "Peso": "2.5 lb" },
    rating: 4.2, reviewCount: 189, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p74", sku: "SKL-20VCIRC", name: "Sierra Circular SKIL 20V 7-1/4\" CR5406",
    slug: "sierra-circular-skil-20v-714",
    description: "Sierra circular SKIL de 7-1/4\" con motor brushless de 20V. Corte profundo de hasta 2-1/2\" a 90°. Freno eléctrico y luz LED. Base de aluminio ajustable. Incluye disco de 24 dientes y batería 2.0Ah.",
    shortDescription: "20V brushless. 7-1/4\". 2-1/2\" corte. Base aluminio. Disco incluido.",
    price: 699.00, comparePrice: null,
    categoryId: "c1-3", brandId: "b15", brand: brands[14], category: categories[0]?.children?.[2] as Category,
    stock: 22, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "20V", "Disco": "7-1/4\"", "Profundidad 90°": "2-1/2\"", "Peso": "5.4 lb" },
    rating: 4.3, reviewCount: 145, isFeatured: true, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p75", sku: "SKL-20VGRIND", name: "Esmeriladora Angular SKIL 20V 4-1/2\" AG9021",
    slug: "esmeriladora-angular-skil-20v",
    description: "Esmeriladora angular SKIL de 4-1/2\" con motor de 20V. Interruptor de gatillo con bloqueo de seguridad. Freno mecánico para detener el disco rápidamente. Incluye disco de corte y 2 baterías 2.0Ah.",
    shortDescription: "20V. 4-1/2\". Freno mecánico. Kit 2 baterías 2.0Ah.",
    price: 549.00, comparePrice: 699.00,
    categoryId: "c1-4", brandId: "b15", brand: brands[14], category: categories[0]?.children?.[3] as Category,
    stock: 28, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "20V", "Disco": "4-1/2\"", "Velocidad": "8,200 RPM", "Peso": "4.1 lb" },
    rating: 4.1, reviewCount: 98, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p76", sku: "SKL-20VHEX", name: "Impacto SKIL 20V 1/4\" Hex CC6810",
    slug: "impacto-skil-20v-14-hex",
    description: "Impacto inalámbrico SKIL de 20V con 1/4\" hex. Hasta 1,400 in-lbs de par de apriete. 2 velocidades con modo de precisión. LED de trabajo. Compacto de 5.6\" de largo para acceso en espacios reducidos.",
    shortDescription: "20V. 1,400 in-lbs. 2 velocidades. 5.6\" largo. LED.",
    price: 449.00, comparePrice: null,
    categoryId: "c1-2", brandId: "b15", brand: brands[14], category: categories[0]?.children?.[1] as Category,
    stock: 40, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "20V", "Par Máximo": "1,400 in-lbs", "Velocidades": "0-1,200 / 0-2,800 RPM", "Longitud": "5.6\"" },
    rating: 4.0, reviewCount: 167, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p77", sku: "SKL-20VJIGSAW", name: "Sierra Caladora SKIL 20V 4495-01",
    slug: "sierra-caladora-skil-20v",
    description: "Sierra caladora SKIL de 20V con motor de 4.5A. 4 posiciones de movimiento pendular para cortes rápidos o limpios. Cambio de hoja sin herramientas con palanca de liberación. Base basculante hasta 45° para cortes en ángulo.",
    shortDescription: "20V. 4 modos pendular. Cambio sin herramientas. Base 45°.",
    price: 499.00, comparePrice: 599.00,
    categoryId: "c1-3", brandId: "b15", brand: brands[14], category: categories[0]?.children?.[2] as Category,
    stock: 32, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "20V", "Corte Madera": "2-5/8\"", "Velocidad": "0-3,000 SPM", "Pendular": "4 posiciones" },
    rating: 4.2, reviewCount: 76, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p78", sku: "SKL-20VKIT3", name: "Kit 3 Herramientas SKIL 20V (Taladro + Sierra + Impacto)",
    slug: "kit-3-herramientas-skil-20v",
    description: "Kit completo de 3 herramientas SKIL 20V: taladro percutor 1/2\", sierra circular 7-1/4\" y impacto 1/4\" hex. Incluye 2 baterías 2.0Ah, cargador doble, maletín de transporte y accesorios. Todo lo que necesitas en un solo kit.",
    shortDescription: "3 herramientas 20V. 2 baterías. Cargador doble. Maletín.",
    price: 1599.00, comparePrice: 1999.00,
    categoryId: "c6", brandId: "b15", brand: brands[14], category: categories[5],
    stock: 15, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "20V", "Herramientas": "3 (taladro, sierra, impacto)", "Baterías": "2x 2.0Ah", "Cargador": "Doble" },
    rating: 4.4, reviewCount: 123, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── Festool Products ──
  {
    id: "p79", sku: "FES-TSC55K", name: "Sierra Circular Festool TSC 55 K 18V 6-1/4\"",
    slug: "sierra-circular-festool-tsc-55-k",
    description: "Sierra circular inalámbrica Festool TSC 55 K de 18V con guía de corte de 55 pulgadas. Motor EC-TEC brushless para máximo rendimiento. Sistema de corte con ahorro de virutas y Adaptador de guía para cortes perfectos.",
    shortDescription: "18V EC-TEC. 6-1/4\". Guía 55\". Ahorro virutas. Brushless.",
    price: 5499.00, comparePrice: 6299.00,
    categoryId: "c1-3", brandId: "b16", brand: brands[15], category: categories[0]?.children?.[2] as Category,
    stock: 6, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Disco": "6-1/4\"", "Guía": "55\" (1400mm)", "Motor": "EC-TEC Brushless" },
    rating: 4.9, reviewCount: 234, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p80", sku: "FES-CT26E", name: "Aspiradora Festool CT 26 E 1200W 26L",
    slug: "aspiradora-festool-ct-26-e",
    description: "Aspiradora Festool CT 26 E con motor de 1200W y capacidad de 26 litros. Sistema SYS-Dock para integración con Systainer. Filtro principal autolimpiante para flujo de succión constante. Arranque automático con herramienta.",
    shortDescription: "1200W. 26L. SYS-Dock. Filtro autolimpiante. Arranque automático.",
    price: 4299.00, comparePrice: null,
    categoryId: "c6", brandId: "b16", brand: brands[15], category: categories[5],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Potencia": "1200W", "Capacidad": "26 litros", "Depresión": "23,500 Pa", "Systainer": "SYS-Dock integrado" },
    rating: 4.8, reviewCount: 178, isFeatured: true, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p81", sku: "FES-DR20TX", name: "Taladro Festool DR 20 TX 18V EC-TEC",
    slug: "taladro-festool-dr-20-tx",
    description: "Taladro sin cable Festool DR 20 TX con motor EC-TEC de 18V. Mandril FastFix de cambio rápido. Sistemas CENTROTEC y BITOOL integrados. Chasis de magnesio para máxima rigidez con peso mínimo. LED de trabajo preciso.",
    shortDescription: "18V EC-TEC. FastFix. CENTROTEC. Magnesio. LED preciso.",
    price: 3899.00, comparePrice: 4499.00,
    categoryId: "c1-1", brandId: "b16", brand: brands[15], category: categories[0]?.children?.[0] as Category,
    stock: 5, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Torque": "67 Nm", "Mandril": "FastFix", "Chasis": "Magnesio" },
    rating: 4.9, reviewCount: 145, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p82", sku: "FES-OF1010", name: "Enrutador Festool OF 1010 EQ 18V 240W",
    slug: "enrutador-festool-of-1010",
    description: "Enrutador compacto Festool OF 1010 EQ de 18V con motor EC-TEC. Rango de velocidad de 10,000-26,500 RPM. Base de precisión con micro-ajuste de 1/256\". Sistema de copiado y guía para trabajos de precisión.",
    shortDescription: "18V EC-TEC. 10,000-26,500 RPM. Micro-ajuste. Base precisión.",
    price: 3299.00, comparePrice: null,
    categoryId: "c1", brandId: "b16", brand: brands[15], category: categories[0],
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Velocidad": "10,000-26,500 RPM", "Potencia": "240W", "Peso": "3.1 kg" },
    rating: 4.7, reviewCount: 98, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p83", sku: "FES-ETS150", name: "Lijadora Excentréntrica Festool ETS EC 150/3 18V",
    slug: "lijadora-excentrica-festool-ets-ec-150",
    description: "Lijadora excentrénica Festool ETS EC 150/3 de 18V con motor EC-TEC. Disco de 150mm y órbita de 3mm para acabado perfecto. Sistema Jetstream de evacuación de polvo. Regulación electrónica de velocidad constante.",
    shortDescription: "18V EC-TEC. 150mm. Órbita 3mm. Jetstream. Velocidad constante.",
    price: 2799.00, comparePrice: 3199.00,
    categoryId: "c1-4", brandId: "b16", brand: brands[15], category: categories[0]?.children?.[3] as Category,
    stock: 7, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Disco": "150mm", "Órbita": "3mm", "Velocidad": "6,000-12,000 RPM" },
    rating: 4.8, reviewCount: 112, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p84", sku: "FES-TS55REQ", name: "Sierra de Corte Festool TS 55 REQ 18V 6-1/4\"",
    slug: "sierra-corte-festool-ts-55-req",
    description: "Sierra de corte Festool TS 55 REQ de 18V con guía de 55 pulgadas. Motor EC-TEC brushless con regulación inteligente de velocidad. Sistema de corte por inmersión con ajuste de profundidad sin herramientas. Guía de precisión incluida.",
    shortDescription: "18V EC-TEC. 6-1/4\". Guía 55\". Corte por inmersión. Guía incluida.",
    price: 4799.00, comparePrice: 5499.00,
    categoryId: "c1-3", brandId: "b16", brand: brands[15], category: categories[0]?.children?.[2] as Category,
    stock: 4, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Voltaje": "18V", "Disco": "6-1/4\"", "Guía": "55\" (1400mm)", "Profundidad Máxima": "2-1/16\"" },
    rating: 4.9, reviewCount: 89, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  // ── JET Products ──
  {
    id: "p85", sku: "JET-JWBS14", name: "Sierra de Cinta JET JWBS-14DXPRO 14\"",
    slug: "sierra-cinta-jet-jwbs-14dxpro",
    description: "Sierra de cinta JET JWBS-14DXPRO de 14 pulgadas con motor de 1-1/4HP. Mesa de hierro fundido con inclinación 45°. Sistema de guía de precisión con soportes de ajuste rápido. Puerta de acero para máxima rigidez.",
    shortDescription: "14\". 1-1/4HP. Mesa fundición 45°. Guía precisión. Acero.",
    price: 4299.00, comparePrice: 4999.00,
    categoryId: "c1-3", brandId: "b17", brand: brands[16], category: categories[0]?.children?.[2] as Category,
    stock: 6, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Capacidad de Corte": "14\"", "Motor": "1-1/4 HP", "Mesa": "Hierro fundido 45°", "Velocidades": "2" },
    rating: 4.7, reviewCount: 145, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p86", sku: "JET-JWL1221", name: "Torno de Banco JET JWL-1221VS 12\" Variable Speed",
    slug: "torno-banco-jet-jwl-1221vs",
    description: "Torno de banco JET JWL-1221VS de 12 pulgadas con velocidad variable electrónica de 60-3,600 RPM. Capacidad sobre banco de 12\" x 16\". Sistema de fijación rápida del eje. Incluye plato de 6\" y soporte de herramienta.",
    shortDescription: "12\". Variable 60-3,600 RPM. Sobre banco 12\"x16\". Plato 6\".",
    price: 2899.00, comparePrice: null,
    categoryId: "c1", brandId: "b17", brand: brands[16], category: categories[0],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Capacidad": "12\" diámetro x 16\" longitud", "Velocidad": "60-3,600 RPM variable", "Motor": "1/2 HP", "Plato": "6\" incluido" },
    rating: 4.6, reviewCount: 98, isFeatured: true, isOnSale: false, isNewArrival: true,
  },
  {
    id: "p87", sku: "JET-JDP17", name: "Taladro de Columna JET JDP-17 17\" 3/4HP",
    slug: "taladro-columna-jet-jdp-17",
    description: "Taladro de columna JET JDP-17 de 17 pulgadas con motor de 3/4HP. Capacidad de taladro en acero de 5/8\". Mesa giratoria 360° con muescas de posicionamiento. Mandril de precisión con rango de 1/16\" a 5/8\".",
    shortDescription: "17\". 3/4HP. 5/8\" acero. Mesa 360°. Mandril 1/16\"-5/8\".",
    price: 3499.00, comparePrice: 3999.00,
    categoryId: "c1-1", brandId: "b17", brand: brands[16], category: categories[0]?.children?.[0] as Category,
    stock: 5, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Distancia Columna-Eje": "17\"", "Motor": "3/4 HP", "Capacidad Acero": "5/8\"", "Mesa": "Giratoria 360°" },
    rating: 4.5, reviewCount: 76, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p88", sku: "JET-JWTS10JF", name: "Sierra de Mesa JET JWTS-10JF 10\" Fenced",
    slug: "sierra-mesa-jet-jwts-10jf",
    description: "Sierra de mesa JET JWTS-10JF de 10 pulgadas con motor de 1-3/4HP. Guía paralela de 30\" con cerradura rápida. Profundidad de corte de 3-1/8\" a 90°. Base de acero abierto para estabilidad. Incluye disco de 40 dientes.",
    shortDescription: "10\". 1-3/4HP. Guía 30\". 3-1/8\" corte. Disco 40 dientes.",
    price: 3199.00, comparePrice: null,
    categoryId: "c1-3", brandId: "b17", brand: brands[16], category: categories[0]?.children?.[2] as Category,
    stock: 7, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Disco": "10\"", "Motor": "1-3/4 HP", "Corte 90°": "3-1/8\"", "Guía": "30\" paralela" },
    rating: 4.4, reviewCount: 67, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p89", sku: "JET-JBG10A", name: "Esmerilador de Banco JET JBG-10A 10\" 3/4HP",
    slug: "esmerilador-banco-jet-jbg-10a",
    description: "Esmerilador de banco JET JBG-10A de 10 pulgadas con motor de 3/4HP. 2 ruedas de esmeril de 10\" x 1\" x 3/4\". Iluminación de trabajo flexible integrada. Restirador de herramientas ajustable montado en base.",
    shortDescription: "10\". 3/4HP. 2 ruedas. Luz LED. Restirador incluido.",
    price: 1299.00, comparePrice: 1499.00,
    categoryId: "c1-4", brandId: "b17", brand: brands[16], category: categories[0]?.children?.[3] as Category,
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Ruedas": "10\" x 1\" x 3/4\"", "Motor": "3/4 HP", "RPM": "3,600", "Restirador": "Ajustable incluido" },
    rating: 4.3, reviewCount: 54, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p90", sku: "JET-JMH5050", name: "Martillo Neumático JET JMH-5050 50 lb",
    slug: "martillo-neumatico-jet-jmh-5050",
    description: "Martillo neumático JET JMH-5050 de 50 libras para demolición pesada. Golpes de 1,900 BPM con energía de impacto de 63 ft-lbs. Mango absorbente de vibración. Ideal para demolición de concreto, asfalto y roca.",
    shortDescription: "50 lb. 1,900 BPM. 63 ft-lbs impacto. Anti-vibración. Demolición.",
    price: 899.00, comparePrice: 1099.00,
    categoryId: "c1", brandId: "b17", brand: brands[16], category: categories[0],
    stock: 15, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Peso": "50 lb", "Golpes": "1,900 BPM", "Impacto": "63 ft-lbs", "Presión": "90-120 PSI" },
    rating: 4.5, reviewCount: 89, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  // ── Knaack Products ──
  {
    id: "p91", sku: "KNA-89", name: "Caja de Herramientas Knaack 89 Storagemaster",
    slug: "caja-herramientas-knaack-89",
    description: "Caja de herramientas Knaack 89 Storagemaster con cuerpo de acero de 16 gauges. Estantes ajustables de acero. Cerradura de cilindro con llave. Apertura frontal completa. Ideal para almacenamiento seguro de herramientas en obra.",
    shortDescription: "Acero 16ga. Estantes ajustables. Cilindro llave. Apertura frontal.",
    price: 999.00, comparePrice: 1199.00,
    categoryId: "c7", brandId: "b18", brand: brands[17], category: categories[6],
    stock: 12, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Material": "Acero 16 gauge", "Capacidad": "48\" x 20\" x 20\"", "Estantes": "Ajustables", "Cerradura": "Cilindro con llave" },
    rating: 4.6, reviewCount: 178, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p92", sku: "KNA-97", name: "Caja de Herramientas Knaack 97 Superstation",
    slug: "caja-herramientas-knaack-97",
    description: "Caja de herramientas Knaack 97 Superstation con 2 puertas y estantes ajustables. Cuerpo de acero de 16 gauges con acabado pólvora. Ruedas neumáticas de 5\" para movilidad. Interior con organizador de bandejas.",
    shortDescription: "2 puertas. Acero 16ga. Ruedas 5\". Organizador bandejas.",
    price: 1299.00, comparePrice: null,
    categoryId: "c7", brandId: "b18", brand: brands[17], category: categories[6],
    stock: 8, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Material": "Acero 16 gauge", "Ruedas": "5\" neumáticas", "Puertas": "2 con cerradura", "Acabado": "Pólvora" },
    rating: 4.5, reviewCount: 134, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p93", sku: "KNA-114", name: "Cesta de Almacenamiento Knaack 114 Sawhorse",
    slug: "cesta-almacenamiento-knaack-114",
    description: "Cesta de almacenamiento Knaack 114 tipo burro de sierra con capacidad de 1,500 lb. Cuerpo de acero de 14 gauges con plegado compacto para transporte. Aberturas para soportar madera y materiales largos.",
    shortDescription: "1,500 lb. Acero 14ga. Plegable. Soporte materiales largos.",
    price: 799.00, comparePrice: 949.00,
    categoryId: "c7", brandId: "b18", brand: brands[17], category: categories[6],
    stock: 15, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Capacidad": "1,500 lb", "Material": "Acero 14 gauge", "Plegado": "Compacto", "Aberturas": "Para materiales largos" },
    rating: 4.4, reviewCount: 98, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p94", sku: "KNA-103", name: "Banco de Trabajo Knaack 103 Rolling Workbench",
    slug: "banco-trabajo-knaack-103",
    description: "Banco de trabajo rodante Knaack 103 con superficie de trabajo de madera de 48\" x 24\". Estructura de acero de 16 gauges con 5 cajones y 2 puertas. Ruedas de 4\" con freno. Cerradura central de seguridad.",
    shortDescription: "48\"x24\" madera. 5 cajones. 2 puertas. Ruedas 4\" freno.",
    price: 1599.00, comparePrice: 1899.00,
    categoryId: "c7", brandId: "b18", brand: brands[17], category: categories[6],
    stock: 6, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Superficie": "48\" x 24\" madera", "Cajones": "5", "Ruedas": "4\" con freno", "Material": "Acero 16 gauge" },
    rating: 4.7, reviewCount: 67, isFeatured: true, isOnSale: true, isNewArrival: false,
  },
  {
    id: "p95", sku: "KNA-109", name: "Estante de Almacenamiento Knaack 109 Shelf",
    slug: "estante-almacenamiento-knaack-109",
    description: "Estante de almacenamiento Knaack 109 de 6 niveles con capacidad de 2,000 lb por repisa. Estructura de acero de 16 gauges con repisas de metal reforzado. Montaje en pared o piso. Ideal para taller u obra.",
    shortDescription: "6 niveles. 2,000 lb/repisa. Acero 16ga. Pared o piso.",
    price: 1099.00, comparePrice: null,
    categoryId: "c7", brandId: "b18", brand: brands[17], category: categories[6],
    stock: 10, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Niveles": "6", "Capacidad/Repisa": "2,000 lb", "Material": "Acero 16 gauge", "Montaje": "Pared o piso" },
    rating: 4.3, reviewCount: 54, isFeatured: false, isOnSale: false, isNewArrival: false,
  },
  {
    id: "p96", sku: "KNA-116", name: "Organizador Modular Knaack 116 Utility Cart",
    slug: "organizador-modular-knaack-116",
    description: "Organizador modular Knaack 116 tipo carrito utilitario con 3 cajones y 1 compartimento abierto. Cuerpo de acero con ruedas de 4\". Cerradura en cada cajón. Ideal para organizar herramientas y accesorios en obra o taller.",
    shortDescription: "3 cajones + 1 abierto. Ruedas 4\". Cerradura por cajón. Acero.",
    price: 899.00, comparePrice: 1049.00,
    categoryId: "c7", brandId: "b18", brand: brands[17], category: categories[6],
    stock: 14, images: ["/images/products/placeholder-tool.jpg"],
    specs: { "Cajones": "3 + 1 abierto", "Ruedas": "4\"", "Cerradura": "Por cajón", "Material": "Acero 16 gauge" },
    rating: 4.5, reviewCount: 78, isFeatured: false, isOnSale: true, isNewArrival: false,
  },
];

// ── Hero Slides ───────────────────────────────────────────
export const heroSlides: HeroSlide[] = [
  {
    id: 1,
    title: "M18 FUEL™ — El Poder Sin Límites",
    subtitle: "Herramientas inalámbricas de mayor rendimiento. Servicio Técnico Oficial Milwaukee Perú.",
    cta: "Ver Colección M18",
    ctaLink: "#",
    image: "/images/hero/hero-1.jpg",
    badge: "NUEVO",
    badgeColor: "bg-itools-red",
  },
  {
    id: 2,
    title: "Ofertas del Mes — Hasta 30% OFF",
    subtitle: "Taladros, impactos, sierras y más. Aprovecha los mejores precios en herramientas profesionales.",
    cta: "Ver Ofertas",
    ctaLink: "#",
    image: "/images/hero/hero-2.jpg",
    badge: "OFERTA",
    badgeColor: "bg-amber-500",
  },
  {
    id: 3,
    title: "Servicio Técnico Oficial Milwaukee",
    subtitle: "Reparación, mantenimiento y garantía. RUC: 20610613749. Atención profesional garantizada.",
    cta: "Conocer Más",
    ctaLink: "#",
    image: "/images/hero/hero-3.jpg",
    badge: "SERVICIO",
    badgeColor: "bg-itools-blue",
  },
];

// ── Helper functions ──────────────────────────────────────
export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getOnSaleProducts(): Product[] {
  return products.filter((p) => p.isOnSale);
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.isNewArrival);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getProductsByCategorySlug(categorySlug: string): Product[] {
  const cat = categories.find((c) => c.slug === categorySlug);
  if (!cat) return [];
  // If it has children, include products from all children
  if (cat.children?.length) {
    const childIds = cat.children.map((c) => c.id);
    return products.filter((p) => p.categoryId && childIds.includes(p.categoryId));
  }
  // Otherwise, return products directly in this category
  const parentCat = categories.find((c) => c.children?.some(ch => ch.slug === categorySlug));
  if (parentCat) {
    const child = parentCat.children!.find((c) => c.slug === categorySlug);
    if (child) return products.filter((p) => p.categoryId === child.id);
  }
  return products.filter((p) => p.categoryId === cat.id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getProductsByBrand(brandId: string): Product[] {
  return products.filter((p) => p.brandId === brandId);
}

export function getTopCategories(): Category[] {
  return categories.filter((c) => !c.parentId);
}

export function getFeaturedBrands(): Brand[] {
  return brands.filter((b) => b.featured);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q) ||
      p.shortDescription.toLowerCase().includes(q) ||
      p.brand?.name.toLowerCase().includes(q)
  );
}

// ── Brand helpers ──────────────────────────────────────────
export const brandThemes: Record<string, { color: string; textColor: string; tabs?: string[] }> = {
  milwaukee: { color: "#D1001C", textColor: "#FFF", tabs: ["M18", "M12", "MX FUEL", "PACKOUT", "FORGE", "PIPELINE", "RED HOT DEALS"] },
  dewalt: { color: "#FFD700", textColor: "#1A1A1A", tabs: ["20V MAX", "12V MAX", "FLEXVOLT", "ATOMIC", "PROFORMANCE"] },
  bosch: { color: "#005691", textColor: "#FFF", tabs: ["18V", "12V", "GREEN", "PROFESSIONAL"] },
  makita: { color: "#0077C8", textColor: "#FFF", tabs: ["18V LXT", "12V CXT", "X2", "LXT 40V"] },
  ego: { color: "#0d5c4a", textColor: "#FFF", tabs: ["56V", "POWER+", "TOOL ONLY"] },
  stanley: { color: "#E35205", textColor: "#FFF", tabs: ["FATMAX", "STANLEY PRO"] },
  "3m": { color: "#CC3300", textColor: "#FFF", tabs: ["SEGURIDAD", "INDUSTRIAL"] },
  "metabo-hpt": { color: "#1b7a3a", textColor: "#FFF", tabs: ["MULTIVOLT", "AIR NAILER"] },
  stihl: { color: "#E35205", textColor: "#FFF", tabs: ["BATERÍA", "GASOLINA"] },
  fein: { color: "#666666", textColor: "#FFF", tabs: ["MULTIMASTER", "SLIPPER"] },
  flex: { color: "#1A1A1A", textColor: "#FFF", tabs: ["24V", "40V MAX"] },
  festool: { color: "#1A1A1A", textColor: "#00A651", tabs: ["SISTEMA", "TSC", "CT"] },
  honda: { color: "#CC0000", textColor: "#FFF", tabs: ["GENERADORES", "MOTORES", "BOMBAS"] },
  "klein-tools": { color: "#FFC220", textColor: "#1A1A1A", tabs: ["ELÉCTRICAS", "MANUALES"] },
  toro: { color: "#1A1A1A", textColor: "#CC0000", tabs: ["CÉSPED", "SOPLORES"] },
  skil: { color: "#CC0000", textColor: "#FFF", tabs: ["12V", "20V"] },
  jet: { color: "#CC0000", textColor: "#FFF", tabs: ["SIERRAS", "TORNO"] },
  knaack: { color: "#8B6914", textColor: "#FFF", tabs: ["ALMACENAMIENTO"] },
};

export function getBrandBySlug(slug: string): Brand | undefined {
  return brands.find((b) => b.slug === slug);
}

export function getProductsByBrandSlug(slug: string): Product[] {
  return products.filter(
    (p) => p.brand?.slug.toLowerCase() === slug.toLowerCase()
  );
}

export function getBrandTheme(slug: string) {
  return brandThemes[slug] || { color: "#333", textColor: "#FFF", tabs: [] };
}