import { brands, categories, products } from "@/lib/data";

export function getFallbackHomeData() {
  const fallbackProducts = products.map((p) => ({
    _id: p.id,
    name: p.name,
    slug: p.slug,
    sku: p.sku,
    brand: p.brand ? { _id: p.brand.id, name: p.brand.name, slug: p.brand.slug } : null,
    category: p.category ? { _id: p.category.id, name: p.category.name, slug: p.category.slug } : null,
    shortDescription: p.shortDescription,
    description: p.description,
    image: { asset: { url: p.images?.[0] || "/images/products/placeholder-tool.jpg" } },
    images: (p.images || []).map((img) => ({ asset: { url: img } })),
    price: p.price,
    salePrice: p.comparePrice && p.comparePrice > p.price ? p.price : undefined,
    stock: p.stock,
    rating: p.rating,
    reviews: p.reviewCount,
    isNewArrival: p.isNewArrival,
    showInTrending: true,
    showInToolCrib: true,
    showInFeatured: p.isFeatured,
    showInNewArrivals: p.isNewArrival,
    showInBestSellers: true,
  }));

  const fallbackCategories = categories.map((c, i) => ({
    _id: c.id,
    name: c.name,
    slug: c.slug,
    iconName: c.icon || "Wrench",
    order: i + 1,
    subcategories: (c.children || []).map((ch) => ({
      name: ch.name,
      link: `/categoria/${ch.slug}`,
    })),
  }));

  const fallbackTrendingCategories = categories.slice(0, 8).map((c, i) => ({
    _id: `tc-${c.id}`,
    name: c.name,
    slug: c.slug,
    iconType: c.icon || "Wrench",
    order: i + 1,
    viewCount: 5000 + i * 850,
  }));

  const fallbackBrandShowcase = brands.map((b, i) => ({
    _id: b.id,
    name: b.name,
    slug: b.slug,
    showInGrid: true,
    order: i + 1,
  }));

  const fallbackDealTiles = [
    {
      _id: "deal-tile-duo-countdown",
      title: "chambeador",
      subtitle: "DEL TIO CHENG",
      href: "/marca/dongcheng",
      countdownEnd: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
      image: { asset: { url: "/banners/sections/duo-chambeador.webp" } },
    },
    {
      _id: "deal-tile-duo-1",
      title: "Herramientas Eléctricas",
      promoPrice: 1039.9,
      href: "/categoria/herramientas-electricas",
      image: { asset: { url: "/banners/sections/dongcheng-combo.webp" } },
    },
    {
      _id: "deal-tile-duo-2",
      title: "Herramientas Inalámbricas",
      promoPrice: 500.0,
      href: "/categoria/herramientas-inalambricas",
      image: { asset: { url: "/banners/sections/dongcheng-combo.webp" } },
    },
    {
      _id: "deal-tile-duo-3",
      title: "Herramientas Manuales",
      promoPrice: 899.0,
      href: "/categoria/herramientas-manuales",
      image: { asset: { url: "/banners/sections/dongcheng-combo.webp" } },
    },
    {
      _id: "deal-tile-duo-4",
      title: "Equipos Especializados",
      promoPrice: 1909.9,
      href: "/categoria/herramientas-manuales",
      image: { asset: { url: "/banners/sections/dongcheng-combo.webp" } },
    },
    {
      _id: "deal-tile-duo-5",
      title: "Accesorios de Herramientas",
      promoPrice: 899.0,
      href: "/categoria/accesorios",
      image: { asset: { url: "/banners/sections/dongcheng-combo.webp" } },
    },
  ];

  const fallbackPromoBanners = [
    {
      _id: "promo-banner-hero-rotomartillo",
      title: "Rotomartillo Milwaukee",
      link: "/marca/milwaukee",
      image: { asset: { url: "/banners/hero/milwaukee-rotomartillo-tall.webp" } },
    },
    {
      _id: "promo-banner-hero-electricista",
      title: "Preventa Electricista",
      link: "/categoria/herramientas-manuales",
      image: { asset: { url: "/banners/hero/preventa-electricista-tall.webp" } },
    },
    {
      _id: "promo-banner-dewalt-powerstack",
      title: "DeWalt Powerstack",
      link: "/marca/dewalt",
      image: { asset: { url: "/banners/sections/dewalt-powerstack.webp" } },
    },
    {
      _id: "promo-banner-mas-vendidos-bg",
      title: "Fondo Los Más Vendidos",
      image: { asset: { url: "/banners/sections/autostyle-banner.webp" } },
    },
    {
      _id: "promo-banner-servicio-tecnico",
      title: "Servicio Técnico Oficial",
      link: "/contacto",
      image: { asset: { url: "/banners/sections/equipos-alta-calidad.webp" } },
    },
    {
      _id: "promo-banner-sata-380",
      title: "Favoritos SATA 380",
      link: "/marca/sata",
      image: { asset: { url: "/banners/sections/dewalt-promo-33.webp" } },
    },
    {
      _id: "promo-banner-exclusiva-1",
      title: "DeWalt Promo 33%",
      link: "/marca/dewalt",
      image: { asset: { url: "/banners/sections/dewalt-promo-33.webp" } },
    },
    {
      _id: "promo-banner-exclusiva-2",
      title: "DeWalt XR Powerpack",
      link: "/marca/dewalt",
      image: { asset: { url: "/banners/sections/dewalt-xr-powerpack.webp" } },
    },
    {
      _id: "promo-banner-hotsale-cocina",
      title: "Equipos Alta Calidad",
      link: "/marca/total",
      image: { asset: { url: "/banners/sections/equipos-alta-calidad.webp" } },
    },
    {
      _id: "promo-banner-taller-autostyle",
      title: "Autostyle Taller",
      link: "/categoria/herramientas-electricas",
      image: { asset: { url: "/banners/sections/autostyle-banner.webp" } },
    },
    {
      _id: "promo-banner-total-530w",
      title: "Total 530W",
      link: "/marca/total",
      image: { asset: { url: "/banners/sections/dongcheng-combo.webp" } },
    },
    {
      _id: "promo-banner-taller-card2",
      title: "Taller Pro 2",
      link: "/categoria/herramientas-electricas",
      image: { asset: { url: "/banners/sections/dewalt-xr-powerpack.webp" } },
    },
    {
      _id: "promo-banner-taller-card3",
      title: "Taller Pro 3",
      link: "/categoria/herramientas-electricas",
      image: { asset: { url: "/banners/sections/equipos-alta-calidad.webp" } },
    },
    {
      _id: "promo-banner-pro-dewalt",
      title: "Ofertas Pro DeWalt",
      link: "/marca/dewalt",
      image: { asset: { url: "/banners/sections/dewalt-xr-powerpack.webp" } },
    },
    {
      _id: "promo-banner-pro-milwaukee",
      title: "Ofertas Pro Milwaukee",
      link: "/marca/milwaukee",
      image: { asset: { url: "/banners/sections/dewalt-promo-33.webp" } },
    },
  ];

  return {
    categories: fallbackCategories,
    trendingCategories: fallbackTrendingCategories,
    heroBanners: [
      {
        _id: "hero-1",
        title: "DeWalt ToughCase",
        link: "/marca/dewalt",
        image: { asset: { url: "/banners/hero/dewalt-toughcase.webp" } },
      },
    ],
    brandPromoBanners: [
      {
        _id: "brand-promo-milwaukee",
        brandName: "Milwaukee",
        link: "/marca/milwaukee",
        image: { asset: { url: "/banners/hero/milwaukee-combo-mid.webp" } },
      },
    ],
    brandShowcase: fallbackBrandShowcase,
    dealTiles: fallbackDealTiles,
    products: fallbackProducts,
    featuredProducts: fallbackProducts.slice(0, 12),
    newArrivals: fallbackProducts.slice(0, 12),
    trendingProducts: fallbackProducts.slice(0, 12),
    promoBanners: fallbackPromoBanners,
    homeSettings: {
      _id: "homeSettings",
      mainCategoriesTitle: "CATEGORIAS PRINCIPALES",
      brandShowcaseTitle: "LAS MEJORES MARCAS PARA TU TRABAJO",
      brandShowcaseSubtitle: "Distribuidor Oficial Autorizado",
      videoSectionTitle: "OFERTAS EN TENDENCIA",
      videoSectionSubtitle: "Videos Demostrativos",
      bestSellersTitle: "LOS MÁS VENDIDOS DEL MES",
      bestSellersSubtitle: "Herramientas con garantía oficial",
      proDealsTitle: "OFERTAS PARA PROFESIONALES",
      proDealsSubtitle: "Precios exclusivos para talleres e industrias",
      equipWorkshopTitle: "EQUIPA TU TALLER",
      equipWorkshopSubtitle: "Todo lo que necesitas en un solo lugar",
      trendingCategoriesTitle: "CATEGORÍAS DE TENDENCIA",
      exclusivePromosTitle: "PROMOCIONES EXCLUSIVAS",
      sataFavoritesTitle: "FAVORITOS DE LOS PROFESIONALES",
      experienceTitle: "VIVE LA EXPERIENCIA ITOOLS",
      whyBuyTitle: "¿POR QUÉ COMPRAR EN ITOOLS.PE?",
      toolCribTitle: "Tool Crib",
      exploreProductsTitle: "Explora Nuestros Productos",
      bestSellersProducts: fallbackProducts.slice(0, 8),
    },
    uiConfig: {
      addToCartText: "Añadir al Carrito",
      viewDetailsText: "Ver Detalles",
      outOfStockText: "Agotado",
      searchPlaceholder: "Buscar herramientas...",
      shippingBadgeText: "Envío a todo Perú",
      securePaymentText: "Pago Seguro",
      warrantyText: "Garantía Oficial",
      returnsText: "Devolución en 30 días",
      marqueeBtn1Text: "¡¡ ENVIOS A TODO EL PERÚ !!",
      marqueeBtn1Link: "/buscar?q=envios",
      marqueeBtn2Text: "¡¡ DESPACHO EN 24H !!",
      marqueeBtn2Link: "/buscar?q=despacho",
      marqueeBtn3Text: "¡¡ RECOJOS INMEDIATOS !!",
      marqueeBtn3Link: "/contacto",
      marqueeBtn4Text: "¡¡ OFERTA DEL DÍA !!",
      marqueeBtn4Link: "/#ofertas-en-tendencia",
      marqueeBtn5Text: "¡¡ ATENCIÓN AL CLIENTE !!",
      marqueeBtn5Link: "https://wa.me/51936085056",
      marqueeBtn6Text: "¡¡ SERVICIO TÉCNICO !!",
      marqueeBtn6Link: "https://wa.me/51936085056",
      marqueeBtn7Text: "¡¡ AYUDA CON MI COMPRA !!",
      marqueeBtn7Link: "https://wa.me/51936085056",
    },
    videoSection: {
      _id: "videoSection",
      sectionTitle: "OFERTAS EN TENDENCIA",
      sectionSubtitle: "Mira nuestras herramientas en acción",
      videos: [],
    },
    promoPopup: null,
  };
}
