import { defineType, defineField } from "sanity";

export default defineType({
  name: "product",
  title: "Producto",
  type: "document",
  fields: [
    defineField({ name: "name", title: "Nombre", type: "string", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "sku",
      title: "SKU / Código de Producto",
      type: "string",
      description: "Código único del producto (ej: MIL-2804-20)",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "brand",
      title: "Marca",
      type: "reference",
      to: [{ type: "brandShowcaseItem" }],
      description: "Referencia a la marca del producto",
    }),
    defineField({
      name: "category",
      title: "Categoría",
      type: "reference",
      to: [{ type: "category" }],
      description: "Categoría principal del producto",
    }),
    defineField({
      name: "shortDescription",
      title: "Descripción Corta",
      type: "string",
      description: "Resumen breve del producto (1-2 líneas, visible en tarjetas y listados)",
    }),
    defineField({
      name: "description",
      title: "Descripción Completa",
      type: "text",
      rows: 5,
      description: "Descripción detallada del producto con todas sus características",
    }),
    defineField({
      name: "image",
      title: "Imagen Principal",
      type: "image",
      options: { hotspot: true },
      description: "Imagen principal del producto (se usa como fallback si no hay imágenes adicionales)",
    }),
    defineField({
      name: "images",
      title: "Galería de Imágenes",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (r) => r.max(10).error("Puedes subir hasta un máximo de 10 imágenes."),
    }),
    defineField({
      name: "price",
      title: "Precio de Venta (S/)",
      type: "number",
      description: "Precio actual de venta en soles",
    }),
    defineField({
      name: "salePrice",
      title: "Precio Oferta (S/)",
      type: "number",
      description: "Precio en oferta (si aplica). Si está vacío, se usa el precio normal.",
    }),
    defineField({
      name: "discountBadge",
      title: "Badge de Descuento (ej: -17%)",
      type: "string",
    }),
    defineField({
      name: "stock",
      title: "Stock Disponible",
      type: "number",
      description: "Unidades disponibles en inventario",
      initialValue: () => 0,
    }),
    defineField({
      name: "rating",
      title: "Rating (estrellas)",
      type: "number",
      validation: (r) => r.min(0).max(5),
    }),
    defineField({
      name: "reviews",
      title: "Número de Reviews",
      type: "number",
    }),
    defineField({
      name: "isNewArrival",
      title: "Nuevo Ingreso",
      type: "boolean",
      initialValue: false,
      description: "Marcar como producto nuevo",
    }),
    defineField({
      name: "specs",
      title: "Especificaciones Técnicas",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            { name: "key", title: "Propiedad", type: "string" },
            { name: "value", title: "Valor", type: "string" },
          ],
          preview: {
            select: { title: "key", subtitle: "value" },
            prepare: ({ title, subtitle }: { title?: string; subtitle?: string }) => ({
              title: title || "Sin propiedad",
              subtitle,
            }),
          },
        },
      ],
      description: "Especificaciones técnicas del producto (ej: Voltaje: 18V, Velocidad: 0-2000 RPM)",
    }),
    defineField({ name: "showInTrending", title: "Mostrar en Tendencias", type: "boolean", initialValue: false }),
    defineField({ name: "showInToolCrib", title: "Mostrar en Tool Crib", type: "boolean", initialValue: false }),
    defineField({ name: "showInFeatured", title: "Mostrar en Destacados", type: "boolean", initialValue: false }),
    defineField({ name: "showInNewArrivals", title: "Mostrar en Nuevos Ingresos", type: "boolean", initialValue: false }),
    defineField({ name: "order", title: "Orden", type: "number", validation: (r) => r.required().min(0) }),
    defineField({ name: "isActive", title: "Activo", type: "boolean", initialValue: true }),
    defineField({
      name: "technicalSheetUrl",
      title: "Ficha Técnica (PDF URL)",
      type: "url",
      description: "URL del PDF de ficha técnica. Puede ser un enlace externo o generado automáticamente.",
    }),
    defineField({
      name: "videoUrl",
      title: "Video URL (YouTube/TikTok)",
      type: "url",
      description: "URL del video del producto (YouTube, TikTok, etc.)",
    }),
  ],
  orderings: [{ title: "Orden", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: { select: { title: "name", subtitle: "sku", media: "image" } },
});
