import { defineType, defineField } from "sanity";

export default defineType({
  name: "uiConfig",
  title: "Configuración Global UI (Textos)",
  type: "document",
  fields: [
    defineField({
      name: "addToCartText",
      title: "Texto de Añadir al Carrito",
      type: "string",
      initialValue: "Añadir al Carrito",
    }),
    defineField({
      name: "viewDetailsText",
      title: "Texto de Ver Detalles",
      type: "string",
      initialValue: "Ver Detalles",
    }),
    defineField({
      name: "outOfStockText",
      title: "Texto de Agotado",
      type: "string",
      initialValue: "Agotado",
    }),
    defineField({
      name: "searchPlaceholder",
      title: "Texto del Buscador",
      type: "string",
      initialValue: "Buscar herramientas...",
    }),
    defineField({
      name: "shippingBadgeText",
      title: "Insignia de Envío",
      type: "string",
      initialValue: "Envío a todo Perú",
    }),
    defineField({
      name: "securePaymentText",
      title: "Insignia de Pago Seguro",
      type: "string",
      initialValue: "Pago Seguro",
    }),
    defineField({
      name: "warrantyText",
      title: "Insignia de Garantía",
      type: "string",
      initialValue: "Garantía Oficial",
    }),
    defineField({
      name: "returnsText",
      title: "Insignia de Devolución",
      type: "string",
      initialValue: "Devolución en 30 días",
    }),
    defineField({
      name: "marqueeBtn1Text",
      title: "Franja Envíos - Texto Botón 1",
      type: "string",
      initialValue: "¡¡ ENVIOS A TODO EL PERÚ !!",
    }),
    defineField({
      name: "marqueeBtn1Link",
      title: "Franja Envíos - Enlace Botón 1",
      type: "string",
      initialValue: "/buscar?q=envios",
    }),
    defineField({
      name: "marqueeBtn2Text",
      title: "Franja Envíos - Texto Botón 2",
      type: "string",
      initialValue: "¡¡ DESPACHO EN 24H !!",
    }),
    defineField({
      name: "marqueeBtn2Link",
      title: "Franja Envíos - Enlace Botón 2",
      type: "string",
      initialValue: "/buscar?q=despacho",
    }),
    defineField({
      name: "marqueeBtn3Text",
      title: "Franja Envíos - Texto Botón 3 (Recojos Inmediatos)",
      type: "string",
      initialValue: "¡¡ RECOJOS INMEDIATOS !!",
    }),
    defineField({
      name: "marqueeBtn3Link",
      title: "Franja Envíos - Enlace Botón 3",
      type: "string",
      initialValue: "/contacto",
    }),
    defineField({
      name: "marqueeBtn4Text",
      title: "Franja Envíos - Texto Botón 4 (Oferta del Día)",
      type: "string",
      initialValue: "¡¡ OFERTA DEL DÍA !!",
    }),
    defineField({
      name: "marqueeBtn4Link",
      title: "Franja Envíos - Enlace Botón 4",
      type: "string",
      initialValue: "/#ofertas-en-tendencia",
    }),
    defineField({
      name: "marqueeBtn5Text",
      title: "Franja Envíos - Texto Botón 5 (Atención Al Cliente)",
      type: "string",
      initialValue: "¡¡ ATENCIÓN AL CLIENTE !!",
    }),
    defineField({
      name: "marqueeBtn5Link",
      title: "Franja Envíos - Enlace Botón 5",
      type: "string",
      initialValue: "https://wa.me/51936085056",
    }),
    defineField({
      name: "marqueeBtn6Text",
      title: "Franja Envíos - Texto Botón 6 (Servicio Técnico)",
      type: "string",
      initialValue: "¡¡ SERVICIO TÉCNICO !!",
    }),
    defineField({
      name: "marqueeBtn6Link",
      title: "Franja Envíos - Enlace Botón 6",
      type: "string",
      initialValue: "https://wa.me/51936085056",
    }),
    defineField({
      name: "marqueeBtn7Text",
      title: "Franja Envíos - Texto Botón 7 (Ayuda con mi Compra)",
      type: "string",
      initialValue: "¡¡ AYUDA CON MI COMPRA !!",
    }),
    defineField({
      name: "marqueeBtn7Link",
      title: "Franja Envíos - Enlace Botón 7",
      type: "string",
      initialValue: "https://wa.me/51936085056",
    }),
  ],
});
